- tests/Phinx/Db/Adapter/MysqlAdapterUnitTest.php
Add real unit tests for mysql adapter, refs #406 issue.
While coding this tests i saw #419, #418 and #417.
Some tricks as:
* implement a child class from real class to test protected/private methods
* make testeable and mockable PDO 
* reimplement method setConnection without typehinting.
This tricks are required for run with fake PDO and capture all message passing.
Some tests are not totally pure unit because have internal 'new' calls:
* testGetColumns has new Column
* testCreateTable* has new Column
The way for resolve this problem is refactoring adapter with dependency injection in parameters but I tried not to be too intrusive. 
Also, we have the folder structure... I didn't know where to put the unit test. 
I think ideal location is test/unit/Phinx/Db/Adapter/MysqlAdapterTest.php …
> Unit tests for mysql adapter 

- src/Phinx/Db/Adapter/AdapterInterface.php
- src/Phinx/Db/Adapter/MysqlAdapter.php
- src/Phinx/Db/Adapter/PostgresAdapter.php
- src/Phinx/Db/Adapter/ProxyAdapter.php
- src/Phinx/Db/Adapter/SQLiteAdapter.php
- src/Phinx/Db/Adapter/SqlServerAdapter.php
- src/Phinx/Db/Adapter/TablePrefixAdapter.php
- tests/Phinx/Db/Adapter/MysqlAdapterTest.php
- add `$limit` parameter to `AdapterInterface::getSqlType`, allowing more complex type hinting
- additional column sizes for "text" and "integer" types now determined by `MysqlAdapter::getSqlType`
- `$limit` is passed through `getSqlType`
Cleans up a some of the changes made in #330:
- remove `PHINX_TYPE_*` constants from `AdapterInterface`
- deprecate `TEXT_SMALL` in favor of `TEXT_TINY` in `MysqlAdapter`
- remove the `classifyTextColumn` method in `MysqlAdapter`
> Add support for different INT sizes to MysqlAdapter, refs #249

- src/Phinx/Db/Adapter/AdapterInterface.php
- src/Phinx/Db/Adapter/AdapterWrapper.php
- src/Phinx/Db/Adapter/PdoAdapter.php
- src/Phinx/Db/Adapter/ProxyAdapter.php
- src/Phinx/Db/Adapter/TablePrefixAdapter.php
- src/Phinx/Db/Adapter/WrapperInterface.php
- src/Phinx/Migration/Manager/Environment.php
- tests/Phinx/Db/Adapter/ProxyAdapterTest.php
- tests/Phinx/Db/Adapter/TablePrefixAdapterTest.php
By creating an abstract wrapper class, we can reduce amount of duplication
between ProxyAdapter and TablePrefixAdapter, while providing a more consistent
interface for future development of additional wrappers.
- Add missing setOptions/getOptions to AdapterInterface
- use AdapterWrapper for TablePrefixAdapter
- use AdapterWrapper for ProxyAdapter
- update ProxyAdapter and TablePrefixAdapter usage in Environment
> Create WrapperInterface and AdapterWrapper, refs #413

- composer.json
PSR-0 is deprecated.
https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-0.md
> Update composer.json to use PSR-4

- docs/configuration.rst
- src/Phinx/Db/Adapter/AdapterFactory.php
- src/Phinx/Migration/Manager/Environment.php
- tests/Phinx/Db/Adapter/AdapterFactoryTest.php
- tests/Phinx/Migration/Manager/EnvironmentTest.php
Builds on #428 by creating a `AdapterFactory` that can be used at any time during application bootstrapping to inject or replace adapters with different classes. This makes it much easier to customize Phinx without direct modification.
> Create AdapterFactory to register and load adapters, refs #413, fixes #388

- src/Phinx/Config/Config.php
- src/Phinx/Config/ConfigInterface.php
- src/Phinx/Console/Command/AbstractCommand.php
- src/Phinx/Console/Command/Create.php
- src/Phinx/Console/Command/Init.php
- src/Phinx/Console/Command/Migrate.php
- src/Phinx/Console/Command/Rollback.php
- src/Phinx/Console/Command/Status.php
- src/Phinx/Console/Command/Test.php
- src/Phinx/Console/PhinxApplication.php
- src/Phinx/Db/Adapter/AdapterInterface.php
- src/Phinx/Db/Adapter/MysqlAdapter.php
- src/Phinx/Db/Adapter/PdoAdapter.php
- src/Phinx/Db/Adapter/PostgresAdapter.php
- src/Phinx/Db/Adapter/ProxyAdapter.php
- src/Phinx/Db/Adapter/SQLiteAdapter.php
- src/Phinx/Db/Adapter/SqlServerAdapter.php
- src/Phinx/Db/Adapter/TablePrefixAdapter.php
- src/Phinx/Db/Table.php
- src/Phinx/Db/Table/Column.php
- src/Phinx/Db/Table/ForeignKey.php
- src/Phinx/Db/Table/Index.php
- src/Phinx/Migration/AbstractMigration.php
- src/Phinx/Migration/IrreversibleMigrationException.php
- src/Phinx/Migration/Manager.php
- src/Phinx/Migration/Manager/Environment.php
- src/Phinx/Migration/MigrationInterface.php
- src/Phinx/Migration/Util.php
- src/Phinx/Wrapper/TextWrapper.php
- src/composer_autoloader.php
> (c) 2014 => (c) 2015

- src/Phinx/Db/Adapter/MysqlAdapter.php
- src/Phinx/Db/Adapter/PdoAdapter.php
- src/Phinx/Db/Adapter/PostgresAdapter.php
- src/Phinx/Db/Adapter/SQLiteAdapter.php
- src/Phinx/Db/Adapter/SqlServerAdapter.php
- tests/Phinx/Db/Adapter/MysqlAdapterTest.php
Currently only SqlServer and PostgreSql support native UUID/UniqueIdentifier column types. This PR adds a mapping for Mysql and Sqlite to treat UUIDs as CHAR(36).
This allows for migration scripts originally written for SqlServer or PostgreSql to work without modification on Mysql/Sqlite.
> Add support for UUID in Mysql and Sqlite

- src/Phinx/Db/Adapter/PdoAdapter.php
Using double quotes for values is MySQL specific.  Running against
a MySQL server with ANSI_QUOTES mode set results in an inability to
record migrations in the database as the migration name value is
treated as a column name.
This change makes the use of single quotes more consistent with all
existing database drivers and more compatible with ANSI usage.
This is more of a bug fix than a feature and will close #453
> Make quotes more ANSI compatible.

- docs/configuration.rst
Hi,
When using sqlsrv to connect to a named instance it had me searching for quite a while to find out that if you connect to an instance it will negotiate which port to use. So you need to omit the port in the configuration.
> Add port information when using sqlsrv adapter

- src/Phinx/Db/Adapter/SQLiteAdapter.php
- tests/Phinx/Db/Adapter/SQLiteAdapterTest.php
Removing a foreign key with SQLite adapter caused the table to be removed. Also the create syntax left out the original column.
> Bugfix: dropForeignKey SQLite adapter

- src/Phinx/Db/Adapter/PostgresAdapter.php
- tests/Phinx/Db/Adapter/PostgresAdapterTest.php
When trying to change the default value in the changeColumn method a syntax error occurred.
Added the ability to drop the default constraint by leaving default null.
> Postgres: fixed problem with changeColumn and default values

- src/Phinx/Db/Adapter/SQLiteAdapter.php
The SQLite adapter uses named indexes (assuming because SQLite needs named indexes), and the current implementation does not use table name as part of the index. This patch changes that.
When two tables define an index on a field with the same name, only one of the indexes is created. No errors are given from Phinx in this case.
A work-around is to use named indexes. (i.e. addIndex(array("field"), array("name" => "my_index")) ).
I've executed the tests after making the change, hoping it won't break anything, let me know if more is required :-)
> Added table name as part of index for SQLite adapter

- tests/Phinx/Db/Adapter/SQLiteAdapterTest.php
This is the test for the previous patch. Two tables with same indexed attribute in SQLite.
> Added test for two indexes with same name in different tables, SQLite.

- docs/migrations.rst
Phinx documentation does not include the function `hasColumn` which is very useful and could help many people write cleaner, smaller code.
> Added documentation for the hasColumn method.

- src/Phinx/Db/Adapter/SQLiteAdapter.php
- tests/Phinx/Db/Adapter/SQLiteAdapterTest.php
This PR contains the following three fixes within the SQLiteAdapter:
Fixed `beginTransaction()` query. It now uses `BEGIN TRANSACTION` (see: https://www.sqlite.org/lang_transaction.html). Using `START TRANSACTION` with PDO error mode set to exception/error (see http://php.net/manual/en/pdo.error-handling.php) will result in an error. Added `testBeginTransaction` test.
Fixed erroneous create table query in `createTable()` when the table has one or more foreign keys.
`createTable()` now adds the foreign key statements to the column definitions, inside the parentheses, instead of after (see: https://www.sqlite.org/lang_createtable.html). Added `testCreateTableWithForeignKey` test.
Fixed two issues in `addForeignKey()`. The `INSERT INTO ... SELECT` query did not contain any column …
> SQLiteAdapter fixes for transaction, createTable() with foreign key and addForeignKey()

- composer.json
Symfony 2.7 has been released and is backward compatible with Symfony 2.6.
Currently the version constraints in composer.json is ~2.6.0, which translates to >=2.6.0,<2.7.
I've made the constraint looser with ~2.6, which translates to >=2.6.0,<3.0
See issue #561
> Looser contraint for Symfony

- src/Phinx/Db/Adapter/MysqlAdapter.php
- tests/Phinx/Db/Adapter/MysqlAdapterUnitTest.php
This pull requests adds support for:
* TINYBLOB
* MEDIUMBLOB
* LONGBLOB
Mostly, using copy paste of the existing TEXT field sizes.
> Add support for BLOB sizes in MySQL (issue #45)

- composer.json
- composer.lock
- src/Phinx/Config/Config.php
- tests/Phinx/Console/PhinxApplicationTest.php
Upgraded the `symfony/console`, `symfony/yaml`, and `symfony/config` libraries to 2.7 so Phinx can be used with Symfony 2.7.
> Upgraded Symfony libraries

- src/Phinx/Db/Adapter/AdapterInterface.php
- src/Phinx/Db/Adapter/PostgresAdapter.php
PostgreSQL 9.4 added [jsonb](http://www.postgresql.org/docs/9.4/static/datatype-json.html) type support. This allows for json stores to be indexed by the engine.
> Added jsonb support for postgresql 9.4

- docs/migrations.rst
A possessive belonging to an "it" doesn't need an apostrophe. Don't believe me? Ask [the Oatmeal](http://theoatmeal.com/comics/apostrophe) (look for the velociraptor)!
> remove Bad Apostrophe from migrations.rst

- docs/migrations.rst
- docs/seeding.rst
* Added ```uuid``` to the list of columns
* Added ```jsonb``` to Postgres
* Sorted column types alphabetically
> Documentation improvements for valid column types

- src/Phinx/Db/Adapter/PostgresAdapter.php
Trying to use my own connection, i've got `Notice: Undefined offset: 0` because i'm using `PDO::FETCH_ASSOC` which doesn't return numeric indexes for its result.
Since we're only interested in one column anyway, we could change it to `PDOStatement::fetchColumn` which would work regardless of the underlying connection and its options.
> simplify check for PostgresAdapter::hasTable

- docs/migrations.rst
- src/Phinx/Db/Adapter/MysqlAdapter.php
- tests/Phinx/Db/Adapter/MysqlAdapterTest.php
This pull request
- Add boolean to array of allowed signed types in the MySQL Adapter - which seems the only adapter the signed option applies to.
- Adds a test for adding an unsigned boolean
- Update docs to indicate boolean and decimal values can be signed when using the MySQL adapter
It fixes #490.
> Allow Boolean Columns to Accept the Signed Option

- src/Phinx/Config/Config.php
- src/Phinx/Config/ConfigInterface.php
- src/Phinx/Console/Command/Create.php
- tests/Phinx/Config/AbstractConfigTest.php
- tests/Phinx/Config/ConfigTest.php
these updates allow you to define templates and classes in the config file instead of having to use --template and --class all the time from the command line. the same rules about not using both at the same time apply. using --class or --template from the cli will overrule the config file.
templates:
file: path/to/file
class: f\q\c\n
> allow setting template file or class in the config file. this time with feeling.

- docs/commands.rst
There is currently no way to fetch database name from PDO connection
object and database name is required in order to check whether a
table exists in the database or not. If PDO connection object
is passed in database PHP configuration file, database name
in `name` key should be passed as well.
This documentation change explains how to use `connection` configuration
key along with `name` key.
> Note about specifying `name` key with `connection`

- docs/configuration.rst
When using charset: utf8 as proposed in the documentation (which works for mysql), SQL Server fails with SQLSTATE[IMSSP]: An invalid encoding was specified for SQLSRV_ATTR_ENCODING.
> Add explanation in regards to the UTF8 charset for SQL Server

- docs/configuration.rst
- src/Phinx/Config/Config.php
- src/Phinx/Console/Command/Create.php
- tests/Phinx/Config/ConfigTest.php
We have a set of migration template creation classes that are namespaced. Allowing them to be accessed via an alias which is part of our Phinx setup simplifies things for our developers.
One thing I wasn't sure about is making ```Config::getAlias()``` part of ```ConfigInterface```.
If I did, any pre-existing class implementing that interface will now require an empty function, assuming they didn't want to use any aliases.
So, hopefully, just where it is is OK.
> Allow aliases for the template creation class names.

- docs/migrations.rst
- src/Phinx/Db/Adapter/PostgresAdapter.php
- tests/Phinx/Db/Adapter/PostgresAdapterTest.php
Added support for numeric columns of type smallint similarly the implementation of column types used in the version of MySQL.
Updated the documentation with the content of the changes made.
Implemented unit testing.
> Support for smallint to PostgreSQL database

- src/Phinx/Db/Adapter/MysqlAdapter.php
Adding support for 'ALTER TABLE ... AFTER ...' feature in changeColumn() for mysql adapter. Used the same as for addColumn(), e.g. $table->changeColumn('colname', 'integer', array('after' => 'anothercolumn')).
> Added support for ALTER TABLE ... AFTER in changeColumn()

- src/Phinx/Db/Adapter/AdapterInterface.php
- src/Phinx/Db/Adapter/MysqlAdapter.php
- src/Phinx/Db/Adapter/PdoAdapter.php
- src/Phinx/Db/Adapter/PostgresAdapter.php
- src/Phinx/Db/Adapter/SQLiteAdapter.php
- src/Phinx/Db/Adapter/SqlServerAdapter.php
- tests/Phinx/Db/Adapter/MysqlAdapterUnitTest.php
Currently, if you define a column as ``binary`` when using the MySQL driver, you get a ``blob``.
The problem is that ``binary`` is a valid type for MySQL and it is currently not possible to get one.
This PR aims to correct this.
A new ``BLOB`` type was added to the constants of the ``AdapterInterface``.
If it is used with other drivers than MySQL, it will produce the same result as using the ``binary`` type.
> Using a binary type with the MySQL driver should produce a binary column

- src/Phinx/Db/Adapter/SQLiteAdapter.php
- tests/Phinx/Db/Adapter/SQLiteAdapterTest.php
Currently, if you define a foreign key constraint with ``ON UPDATE`` and ``ON DELETE`` statements in SQLite, under specific circumstances, the constraint drop results in an error as the new table is not created.
Take the example I added in the SQLiteAdapterTest file.
Given how the constraints are added, the create script is :
```sql
CREATE TABLE `table` (
`id` INTEGER NULL PRIMARY KEY AUTOINCREMENT,
`ref_table_id` INTEGER,
`ref_table_field` VARCHAR(255),
FOREIGN KEY (`ref_table_field`) REFERENCES `ref_table` (`field1`) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (`ref_table_id`) REFERENCES `ref_table` (`id`)
)
```
When this query is fed to the ``preg_replace()`` call that was modified in the SQLiteAdapter if a ``dropForeignKey('table', array('ref_table_field'))`` is done, it will …
> Fix dropForeignKey for SQLite

- src/Phinx/Console/Command/Migrate.php
- tests/Phinx/Console/Command/MigrateTest.php
According to issue #650, database name **is** required for some commands (in particular migrate). There is currently no check that this required parameter is actually set. This change would address that issue.
> Display error if database name can't be determined.

- src/Phinx/Db/Adapter/MysqlAdapter.php
- tests/Phinx/Db/Adapter/MysqlAdapterTest.php
- tests/Phinx/Db/Adapter/MysqlAdapterUnitTest.php
The methods hasIndex, dropIndex and hasForeignKey fail to identify
index/keys correctly when using column names.
See #187
> Fixed key/index operations for MySQL

- docs/commands.rst
- src/Phinx/Console/Command/Status.php
- src/Phinx/Migration/Manager.php
- tests/Phinx/Console/Command/StatusTest.php
- tests/Phinx/Migration/ManagerTest.php
Status command exit codes:
0: all migrations are up
1: at least one migration is down
2: at least one migration is missing
Fixes robmorgan/phinx#676
> Status Command now returns proper exit code

- composer.json
- docs/configuration.rst
I've locally bumped phinx to use Symfony3 and all the tests pass.
To me it looks like phinx work out of the box with the soon to be released so I propose to make the `composer.json` compatible with it.
> Added support for Symfony3

- src/Phinx/Db/Adapter/PostgresAdapter.php
If the error message contains a percent sign, the code would fail, this fixes that.
> fix sprintf call

- index.html
``vendor/bin`` contains executable/runnables. Using ``php`` to launch them is incorrect.
> vendor/bin contains executable/runnables.

- .travis.yml
As composer.json says PHP must be >= 5.4, no point in testing against PHP 5.3.
> PHP 5.3 is no longer supported by phinx.

- tests/Phinx/Console/Command/InitTest.php
- tests/Phinx/Console/Command/MigrateTest.php
- tests/Phinx/Console/Command/RollbackTest.php
- tests/Phinx/Console/Command/SeedCreateTest.php
- tests/Phinx/Console/Command/SeedRunTest.php
- tests/Phinx/Console/Command/StatusTest.php
- tests/Phinx/Migration/ManagerTest.php
Will probably also affect ConEMU and other tools that add ANSI colouring automatically (i.e. without a --ansi option) that cannot (seemingly) be disabled when running phpunit.
I based this (as requested) on the tag v0.5.0 and not 0.5.x-dev. But seeing the "Can't automatically merge".
No idea how to handle that.
> Stop decorating output. This affects Windows users running ANSICON.

- docs/migrations.rst
The documentation for "Creating a Table" was using CURRENT_TIMESTAMP on a datetime field instead of a timestamp field.
> Updated migrations.rst to correct usage of CURRENT_TIMESTAMP.

- tests/Phinx/Migration/ManagerTest.php
Stop Symfony Console from decorating output when running unit tests and testing for specific content in the output.
> Stop decorating output

- src/Phinx/Console/Command/Migrate.php
- tests/Phinx/Console/Command/MigrateTest.php
Hi. I just made it so that it returns 1 if the environment doesn't exist, and 0 for everything else.
It would probably be nicer to get a status from the actual migrations to see if they ran correctly, but I haven't looked into that.
> Migrate::execute() now returns exit code

- docs/configuration.rst
- src/Phinx/Migration/Manager.php
I just enable `GLOB_BRACE` to capture migrations in multiple directories.
Example:
```php
<?php
return [
'paths' => [
'migrations' => '%%PHINX_CONFIG_DIR%%/module/Module{A,B}/migrations',
],
];
```
> Capturing migrations with GLOB_BRACE

- docs/migrations.rst
The 'tables' section had become difficult to navigate and find information quickly, so I've broken it down into 4 discrete sections:
- Tables
- Columns
- Indexes
- Foreign Keys
> Break into tables documentation into logical sections

- src/Phinx/Db/Adapter/PdoAdapter.php
When using the `-vv` and `-vvv` flags, there was no output from the command.
> Continue to produce output at higher verbosities

- src/Phinx/Db/Adapter/AdapterInterface.php
- src/Phinx/Db/Adapter/AdapterWrapper.php
- src/Phinx/Db/Adapter/PdoAdapter.php
- src/Phinx/Db/Adapter/PostgresAdapter.php
- src/Phinx/Db/Adapter/SqlServerAdapter.php
- src/Phinx/Migration/Manager.php
- src/Phinx/Migration/Manager/Environment.php
- tests/Phinx/Migration/ManagerTest.php
Resolves #543 
To reduce the time it takes to locate which branch of code contains a missing migration, all migration names are now stored in the phinxlog table. These are now used as a fall-back reference when the status command is run.
**Example**
This image shows how even though this branch doesn't currently contain a previously migrated migration, the name still shows up in the status log:
> Show names of missing migrations in status log

- src/Phinx/Db/Adapter/PdoAdapter.php
This is because existing users of Phinx will not have values for this column, and so it should correctly specify that it is expecting to have null values. Should fix #803.
> Allow nulls in migration name column

- src/Phinx/Migration/Manager.php
Hi!
Some systems, particularly non-GNU, don't support `GLOB_BRACE` constant and migrations on those systems fail miserably. Since the feature is not critical for Phinx to work and, in fact, migration path is always set by a end-developer, I think the library should use the `GLOB_BRACE` constant only when it's available in the operating system.
This is my tiny pull request that changes this behavior and introduces a check if `GLOB_BRACE` constant is present. If not, it just passes `0` as `$flags` argument for `glob()` function.
Please merge, if you're happy with it.
Best,
Bartosz
> Use GLOB_BRACE constant only if it's available

- src/Phinx/Console/Command/SeedRun.php
This PR adds in a simple update to allow for running multiple seeds at once.
Currently the seed command allows you to specify which you'd like to run with the `-s` command line flag like:
```
vendor/bin/phinx seed:run -s UserCreate
```
With this PR, multiple seeds can be defined here using a comma-separated list:
```
vendor/bin/phinx seed:run -s UserCreate,ProductCreate
```
The seeds are then run in that order (as opposed to the normal `seed:run` that just does them in the order `glob` finds them in).
> Provide the ability to run multiple seeds at once (in the given order)

- src/Phinx/Db/Adapter/SQLiteAdapter.php
- tests/Phinx/Db/Adapter/SQLiteAdapterTest.php
SQLite has dynamic types, and no support for ENUMs. This PR adds support for ENUMs using CHECK(). This allows us to at least ensure the data that is inserted is OK.
To give an idea of what it generates:
```sql
CREATE TABLE "node_rev" (
`nodeID`	INTEGER  PRIMARY KEY AUTOINCREMENT,
`nodeType`	ENUM CHECK(nodeType IN ( 'block' , 'relation' , 'parameter' , 'validation' , 'transformation' , 'model' , 'experiment' , 'image' , 'text' ))
)
```
> Add support for SQLite enums using CHECK().

- src/Phinx/Console/Command/SeedRun.php
- tests/Phinx/Console/Command/SeedRunTest.php
[This pull request](https://github.com/robmorgan/phinx/pull/821) introduces a bug that makes it impossible to run all the existing seed(ers). This one fixes it.
Surprisingly enough, the previous fix, according to the [Version History](https://github.com/robmorgan/phinx#version-history) has been included in version `0.5.4` which was never released (it's not available in [packagist](https://packagist.org/packages/robmorgan/phinx)).
> "[InvalidArgumentException] The seed class "" does not exist" when trying to run all the available seeds

- docs/commands.rst
- src/Phinx/Console/Command/Breakpoint.php
- src/Phinx/Console/PhinxApplication.php
- src/Phinx/Db/Adapter/AdapterInterface.php
- src/Phinx/Db/Adapter/AdapterWrapper.php
- src/Phinx/Db/Adapter/PdoAdapter.php
- src/Phinx/Db/Adapter/PostgresAdapter.php
- src/Phinx/Db/Adapter/SqlServerAdapter.php
- src/Phinx/Migration/Manager.php
- tests/Phinx/Migration/ManagerTest.php
Allow breakpoints to be set to stop accidental rollbacks. When a breakpoint is set, rollback will stop when it reaches that migration.
Can be overridden with --force.
Replaces PR https://github.com/robmorgan/phinx/pull/700 and is based upon 0.6.x-dev
> Introduce breakpoint support for rollbacks

- src/Phinx/Db/Adapter/AdapterWrapper.php
- src/Phinx/Db/Adapter/MysqlAdapter.php
- src/Phinx/Db/Adapter/PdoAdapter.php
- src/Phinx/Db/Adapter/PostgresAdapter.php
- src/Phinx/Db/Adapter/SQLiteAdapter.php
- src/Phinx/Db/Adapter/SqlServerAdapter.php
Introduces a new method \Phinx\Db\Adapter\PdoAdapter::castToBool()
By default, 0 and 1 are fine for mysql, sqlite and sqlsrv for boolean types.
Postgres must use true and false for boolean types.
Fixes/replaces PR #876
> Standardise the breakpoint related queries

- .travis.yml
- composer.json
- tests/Phinx/Db/Adapter/MysqlAdapterUnitTest.php
The pre-built/installed version of PHPUnit that is run doesn't seem to have an uptodate version of php-token-stream.
So, rather than using that version, run with the composer provided version.
> Fix failing phpunit for hhvm

- src/Phinx/Db/Table/Column.php
- src/Phinx/Db/Table/ForeignKey.php
- src/Phinx/Db/Table/Index.php
- tests/Phinx/Db/Table/ColumnTest.php
- tests/Phinx/Db/Table/ForeignKeyTest.php
- tests/Phinx/Db/Table/IndexTest.php
This check makes sure the developer gets an appropriate message.
> When setting options as a non-associative array, Column fails with "Call to undefined method Phinx\Db\Table\Column::set0()"

- docs/migrations.rst
Only `removeIndex()` was mentioned in the docs. 
It took me quite a while to figure out that it expected the field names (and not the index names), so I'm adding the reference.
> Added mention to removeIndexByName()

- src/Phinx/Config/Config.php
- tests/Phinx/Config/ConfigTest.php
Ran into an issue where if the `migration_base_class` option is specified without a namespace, the class name returned empty in the migration generation.
> Fix for Config::getMigrationBaseClassName

- .gitignore
Changing the db and migrations directories to non-relative paths as per 89f4fa27b302a6234b9676fa2bce2af83198e1bd resulted in a user with `core.ignorecase=true` in his git config having issues with files and folders within his vendor folder to be ignored #965.
> Reverse "fix .gitignore"

- docs/configuration.rst
- src/Phinx/Console/Command/AbstractCommand.php
- tests/Phinx/Console/Command/AbstractCommandTest.php
- tests/Phinx/Console/Command/Asset/FindConfigTestCommand.php
- tests/Phinx/Console/Command/Asset/app-test/config/phinx.php
- tests/Phinx/Console/Command/Asset/env-test/phinx.php
Features added:
- ability to provide PHINX_CONFIG_DIR to scan
- ability to traverse one level deep looking for matching config
Thoughts on including this?
The motivation is to allow the config files to live outside of root, but also in a discoverable place.  The idea behind the environment variable is so that isolated development environments (virtual, docker compose), can specify the migration directory (should be be more than 1 level deep).
> Config File Location Feature

- .gitattributes
Added `.gitattributes` to exclude the tests on export - e.g. when pulled in via composer.
> Add gitattributes to exclude tests folder

- docs/migrations.rst
Closes #823 as it's possible to change the constraint name.
> Mention constraint name change in docs

- src/Phinx/Wrapper/TextWrapper.php
Fixes TextWrapper which was unable to accept seed name correctly due to SeedRun::execute always expecting an array
> Fix seed command accepting string

- src/Phinx/Db/Adapter/SQLiteAdapter.php
- tests/Phinx/Db/Adapter/SQLiteAdapterTest.php
In some cases, data insertion with sqlite driver doesn't work.
- if data insertion contains a single quote, data isn't inserted in table.
- if null value is sent, data will be converted to empty string. "IS NULL" operator will not work.
I attach a migration example.
[20160330000000_sqlite_insertion_issue.txt](https://github.com/robmorgan/phinx/files/195077/20160330000000_sqlite_insertion_issue.txt)
> fix(pdo_sqlite): Handles correctly data insertions

- src/Phinx/Console/Command/Create.php
Nothing much to say besides I get annoyed as I never remember if the migrations should be snake_case as the file or CamelCase as the class. A tip about that on the help could be useful, instead of hitting the errorwall :)
> Adding hint on migration name in CamelCase

- src/Phinx/Db/Adapter/PostgresAdapter.php
Added some code to create geography fields like this
```
geography(geometry, 4326)
geography(POLYGON, 4326)
```
Any comments welcome
> PostgreSQL - improve geography types creation

- .travis.yml
- phpstan.neon
- src/Phinx/Config/Config.php
- src/Phinx/Config/ConfigInterface.php
- src/Phinx/Console/Command/Create.php
- src/Phinx/Db/Adapter/AdapterInterface.php
- src/Phinx/Db/Adapter/AdapterWrapper.php
- src/Phinx/Db/Adapter/PdoAdapter.php
- src/Phinx/Db/Adapter/PostgresAdapter.php
- src/Phinx/Db/Adapter/SqlServerAdapter.php
- src/Phinx/Db/Adapter/TablePrefixAdapter.php
- src/Phinx/Db/Table.php
- src/Phinx/Db/Table/Column.php
- src/Phinx/Db/Table/ForeignKey.php
- src/Phinx/Migration/AbstractMigration.php
- src/Phinx/Migration/Manager/Environment.php
- src/Phinx/Seed/AbstractSeed.php
- src/Phinx/Seed/SeedInterface.php
- src/Phinx/Util/Util.php
- src/Phinx/Wrapper/TextWrapper.php
- tests/Phinx/Db/Adapter/MysqlAdapterTest.php
- tests/Phinx/Db/Adapter/PostgresAdapterTest.php
- tests/Phinx/Db/Adapter/SQLiteAdapterTest.php
- tests/Phinx/Db/Adapter/TablePrefixAdapterTest.php
- tests/Phinx/Util/UtilTest.php
I ran [PHPStan](https://github.com/phpstan/phpstan) on your codebase and it found these issues. Feel free to comment on the fixes. I think it'd also to be beneficial to integrate PHPStan into your Travis build so you can prevent these errors in the future.
You can find out more about [PHPStan on Medium.com](https://medium.com/@ondrejmirtes/phpstan-2939cd0ad0e3).
> Fixing issues found by PHPStan & Integrating PHPStan

- src/Phinx/Db/Adapter/PostgresAdapter.php
- tests/Phinx/Db/Adapter/PostgresAdapterTest.php
The `$this->quoteColumnName` call is missing for `$newColumnName` in `PostgresAdapter`.
This results in bad behavior, for example `renameColumn('created_at', 'createdAt')` results in `createdat` column name in database.
> Quote new column name in renameColumn in PostgresAdapter

- phpunit.xml.dist
- src/Phinx/Db/Adapter/PdoAdapter.php
- tests/Phinx/Migration/ManagerTest.php
This is a bug fix issue #1047
@todo Amend the start_time column to NOT be automatically update when the
phinxlog row is amended.
> Do not allow the start_time to be updated when setting a breakpoint

- src/Phinx/Db/Adapter/PdoAdapter.php
hasn't broken anything - locally all tests pass, but only able to test
mysql.
> Test that the removal of the default on the phinxlog timestamp columns

- docs/commands.rst
- docs/configuration.rst
- phinx.yml
- src/Phinx/Config/Config.php
- src/Phinx/Config/ConfigInterface.php
- src/Phinx/Console/Command/Rollback.php
- src/Phinx/Console/Command/Status.php
- src/Phinx/Db/Adapter/AdapterInterface.php
- src/Phinx/Db/Adapter/PdoAdapter.php
- src/Phinx/Migration/Manager.php
- src/Phinx/Migration/Manager/Environment.php
- tests/Phinx/Config/ConfigTest.php
- tests/Phinx/Console/Command/RollbackTest.php
- tests/Phinx/Console/Command/StatusTest.php
- tests/Phinx/Db/Adapter/PdoAdapterTest.php
- tests/Phinx/Migration/ManagerTest.php
A new Configuration option named `version_order` was added. Its possible values are:
- `creation` (the default): causes the Rollback and Status commands to order the executed migrations by their Creation Times (aka Migration IDs or Names).
- `execution`: causes the Rollback and Status commands to order the executed migrations by their Execution Times (aka Start Times).
This means that when invoking the Rollback command:
- With an `execution` version order, the last executed migration will be rollbacked.
- With an `execution` version order and a `-d (date)` option, the migration start times will be used to determine the target version to rollback to. In other words, all migrations which were executed after that date will be rollbacked.
- With an `execution` version order and a `-t (target …
> Rollbacks by start time

- src/Phinx/Wrapper/TextWrapper.php
Fix: #959 
Call parameters '-e', '-c' and '-p' only when they have a value.
Also remove default environment. Running without environment is handled by the commands itself:
https://github.com/robmorgan/phinx/blob/master/src/Phinx/Console/Command/Status.php#L76
https://github.com/robmorgan/phinx/blob/master/src/Phinx/Console/Command/Migrate.php#L79
https://github.com/robmorgan/phinx/blob/master/src/Phinx/Console/Command/Rollback.php#L92
https://github.com/robmorgan/phinx/blob/master/src/Phinx/Console/Command/SeedRun.php#L77
> Fix TextWrapper (#959)

- src/Phinx/Console/Command/AbstractCommand.php
Fix: #960 
The commands get a fresh InputInterface and OutputInterface Instance for each time, the command runs. But the commands cache the Manager instance, which gets a reference to the Input/OutputInterface on construction. So when the command runs a second time, they get fresh Input/OutputInterfaces but uses the cached Manager Instance with reference to old Input/OutputInterface Instances.
This PR updates the Input and OutputInterface of the cached Manager to the Input/OutputInterface of the current command run. (See #960 comment for more details)
> Update Input- and OutputInterface on cached Manager

- src/Phinx/Migration/Manager.php
- tests/Phinx/Migration/ManagerTest.php
Fix #1059
I think error comes with this commit: https://github.com/robmorgan/phinx/commit/bba44b381fef9756c1d2f5a6c65ddc6757e7f6bb
If only only migration is left the first migration is selected as target instead of 0. So nothing is done.
I found a test case for this, but don't know why the test does not work:
https://github.com/robmorgan/phinx/blob/master/tests/Phinx/Migration/ManagerTest.php#L712
> Fix rollback on only one migration

- .travis.yml
This issue drops support for HHVM from Phinx.
> Fixes #1101. Drop HHVM support.

- docs/migrations.rst
- src/Phinx/Db/Adapter/MysqlAdapter.php
- tests/Phinx/Db/Adapter/MysqlAdapterTest.php
- tests/Phinx/Db/Adapter/MysqlAdapterUnitTest.php
Just new pull request for #658 made by @Serhioromano. Very useful feature.
Are additional tests required?
> Allow to pass table option signed for primary key

- src/Phinx/Console/Command/Create.php
before:
```
➔ ./vendor/bin/phinx create InitialData
Phinx by Rob Morgan - https://phinx.org. version 0.8.0
using config file ./phinx.php
using config parser php
using migration paths 
- /tmp/jura/db/migrations
using migration base class Phinx\Migration\AbstractMigration
using default template
created /db/migrations/20170428180919_initial_data.php
➔ git add /db/migrations/20170428180919_initial_data.php
fatal: Could not switch to '/db/': No such file or directory
➔
```
after:
```
➔ ./vendor/bin/phinx create InitialData
Phinx by Rob Morgan - https://phinx.org. version 0.8.0
using config file ./phinx.php
using config parser php
using migration paths 
- /tmp/jura/db/migrations
using migration base class Phinx\Migration\AbstractMigration
using default template
created …
```
> make create command output copy-paste friendly

- src/Phinx/Db/Adapter/AdapterWrapper.php
- src/Phinx/Db/Adapter/TablePrefixAdapter.php
use the table_prefix option, i found an error.
$table = $this->table('user');
$table->truncate();
PHP Fatal error: Uncaught Error: Cannot call abstract method Phinx\Db\Adapter\AdapterInterface::truncateTable()
> fixed miss method and return type error

- src/Phinx/Db/Adapter/PostgresAdapter.php
- tests/Phinx/Db/Adapter/PostgresAdapterTest.php
Issue similar to https://github.com/robmorgan/phinx/pull/1041
The `addIndex` method did not quote the column names, which resulted in error if one of the columns being added to the index was camel case.
Test provided.
> Quote column names in the addIndex() method - Postgres

- src/Phinx/Migration/Manager/Environment.php
- tests/Phinx/Migration/Manager/EnvironmentTest.php
If someone uses an unconfigured PDO instance as a connection migration won't stop if an error is encountered (by default pdo is set to PDO::ERRMODE_SILENT)
Add a PDO attribute to throw an exception on failed queries.
> Force exception onto PDO

- docs/migrations.rst
The Description in the preceding documentation says `query()` will return a PDO Statement, but the sample code and comment implies it will return an array instead.
> Correct `Migration->query($sql)` Example

- src/Phinx/Db/Adapter/SQLiteAdapter.php
This fixes an issue in the SQLiteAdapter that causes columns to be destroyed when removing a default value of `''` from a string column.
See comment here: https://github.com/cakephp/phinx/pull/1093#issuecomment-312373192
Unfortunately, there are no existing tests for this specific functionality that prove what I've changed hasn't broken anything.
> [SQLite] Fix invalid changeColumn regex causing deletions

- src/Phinx/Db/Adapter/PdoAdapter.php
- src/Phinx/Db/Adapter/SQLiteAdapter.php
- tests/Phinx/Db/Adapter/SQLiteAdapterTest.php
- tests/Phinx/Migration/Manager/EnvironmentTest.php
Fix for the regex issue found (#1086) in `Phinx\Db\Adapter\SQLiteAdapter::dropColumn()` which resulted in malformed SQL being executed.  Note that included in this fix is a call to set the PDO error mode to throw exceptions in the event of error (malformed SQL being executed, etc) as I believe this will make such errors much more visible in the future (there were some failing unit tests that were covered up and marked as passing because of the exact same problem...malformed SQL being executed but no exceptions being thrown and no error codes checked for).  This was done in the `Phinx\Db\Adapter\PdoAdapter::setConnection()` method, so it will apply to all adapter classes derived from it.  I wanted to call this to attention as I'm not 100% certain this omission wasn't by design.  Let me …
> Fix issue with dropColumn command in SQLite (#1086)

- src/Phinx/Db/Adapter/SQLiteAdapter.php
Related to https://github.com/cakephp/phinx/pull/1093 - this PR modifies the original RegEx that was used for dropping columns.
The issue was that ENUMs weren't properly caught by the RegEx and thus produced invalid SQL when re-creating the table. This regex should fix that.
> SQLite - Revert back to RegEx for dropping enum columns (#1086)

- phinx.yml
Hi, getting a php non fatal error being shown in error_get_last() due to a symfony deprecation.
Not quoting the scalar "%%PHINX_CONFIG_DIR%%/database/migrations" starting with the "%" indicator character is deprecated since Symfony 3.1 and will throw a ParseException in 4.0.
Info about this error: http://symfony.com/blog/new-in-symfony-3-1-yaml-deprecations#deprecated-starting-scalars-with-characters
> Update yml file to surround parameters with quotes

- src/Phinx/Db/Adapter/PostgresAdapter.php
- tests/Phinx/Db/Adapter/PostgresAdapterTest.php
Bug: pgsql adapter doesn't allow to add comments to columns if table or column has name matching one of reserved keywords (such as `user`).
Proposed fix: add quoting for table name and column name.
> Fix pgsql quoting in comment clause

- src/Phinx/Db/Adapter/PostgresAdapter.php
Have I implemented my feature for as many database adapters as possible? No, it is to correct a bug on postgresql
Does my new feature improve Phinx's performance or keep it consistent? No change
Does my feature fit within the database migration space? ???
Is the code entirely my own and free from any commercial licensing? Yes
Am I happy to release my code under the MIT license? Yes
Is my code formatted using the PSR-2 coding standard? Yes
> Postgresql can't have limit on bigint, same as integer and smallint

- CONTRIBUTING.md
- docker-compose.yml
- docker/Dockerfile
- docker/entrypoint.bash
When I was trying to contribute to phinx, I found it rather difficult to setup the testing environment for running the unit tests.
This is why I have decided to create [docker](https://www.docker.com) and [docker-compose](https://docs.docker.com/compose/) files to help you kickstart a development environment. 
The advantage of using docker for developing is that running `docker-compose run phinx` will bring up a freshly created MySQL 5.5 and Postgres 9.2 database (the versions can be easily adjusted in `docker-compose.yml`), and a PHP 5.4 container running the unit tests. The PHP 5.4 container uses CentOS 7. I chose CentOS 7 since it still supports (and maintains PHP 5.4, unlike the official docker image) and I chose PHP 5.4 because it is the oldest PHP version supported by phinx.
So, …
> Docker Development Kickstart

- docs/migrations.rst
According to [the docs](https://github.com/cakephp/phinx/blob/26ac87ba6562e83689d34e3460ccc1d8014008d3/docs/migrations.rst#creating-a-table): *(emphasis mine)*
>The `id` option sets the name of the automatically created identity field, while the `primary_key` option selects the field or fields used for primary key. **The `primary_key` option always defaults to the value of `id`. Both can be disabled by setting them to false.**
This is misleading for two reasons.
First, the `primary_key` is currently only accounted for when `id` is set false, otherwise it's being set to the same value as `id`.  `primary_key` is not "inheriting" the value, that'd mean that there should be an `isset()` check before `$options['primary_key'] = $options['id']`.
Second, trying to run `vendor/bin/phinx migrate` …
> Update docs to reflect actual behavior of [primary_key => false]

- src/Phinx/Migration/Manager.php
- tests/Phinx/Migration/ManagerTest.php
This replaces PR #939.
There is a bug where a any number less than the first migration time stamp (or a typo) supplied to the `--target` option will cause all migrations to be rolled back. Referring to PR #939, I don't think this should be the case and optimistically the `--target` option should actually take the migration name, not the migration id (time stamp) because this functionality is basically incorporated into `--date`. 
What this pull request does is add an explicit check for `all` or `0` passed to the `--target` option to trigger a rollback of all migrations. This doesn't allow typos or small numbers to incorrectly rollback all.
Going forward, I would either prefer the `--target` functionality be changed to take the name, or a new option be added to specify the name. Either …
> Rollback --target using migration name

- docs/commands.rst
Code block was loosed because no empty line after .. code-block:: php
> Fixed documentation example of usage phpunit

- src/Phinx/Db/Adapter/MysqlAdapter.php
- tests/Phinx/Db/Adapter/MysqlAdapterTest.php
When we create enum's in DB we should be able to read their's values back in migrations too.
> Fill up column values from schema

- src/Phinx/Db/Adapter/AdapterInterface.php
- src/Phinx/Db/Adapter/AdapterWrapper.php
- src/Phinx/Db/Adapter/PdoAdapter.php
- src/Phinx/Db/Adapter/TablePrefixAdapter.php
- src/Phinx/Db/Adapter/TimedOutputAdapter.php
- src/Phinx/Db/Table.php
- tests/Phinx/Db/Adapter/MysqlAdapterTest.php
- tests/Phinx/Db/Adapter/PostgresAdapterTest.php
- tests/Phinx/Db/Adapter/SQLiteAdapterTest.php
- tests/Phinx/Db/Adapter/SqlServerAdapterTest.php
- tests/Phinx/Db/Adapter/TablePrefixAdapterTest.php
- tests/Phinx/Db/TableTest.php
- tests/Phinx/Migration/AbstractMigrationTest.php
When execute command `seed:run`, insert all data to a table in a bulk.
It take much time to insert data to a table one by one until now.
An example is shown below:
```
$table = $this->table('users');
$table->bulk()
->insert($data)
->save();
```
It became more than triple as fast by Bulk Insert when inserting 1,000 records.
It is very effective when many data samples are required.
However, it is assumed that the keys of data to be set are unified. 
The method `bulk()` are not available in the following example:
```
$data = array(
array(
'column1' => 'value1',
'column2' => 1,
),
array(
'column1' => 'value2',
'column3' => 'foo',
),
array(
'column1' => 'value3',
'column2' => 3,
'column3' => 'foo',
)
);
$table = $this->table('users');
$table->bulk()
->insert($data)
->save();
```
The function …
> When execute command `seed:run`, insert all data to a table in a bulk.

- src/Phinx/Migration/AbstractMigration.php
- src/Phinx/Migration/Manager/Environment.php
- src/Phinx/Migration/MigrationInterface.php
- tests/Phinx/Migration/ManagerTest.php
- tests/Phinx/Migration/_files/reversiblemigrations/20170824134305_direction_aware_reversible_up.php
- tests/Phinx/Migration/_files/reversiblemigrations/20170831121929_direction_aware_reversible_down.php
Enables otherwise irreversible migrations to become reversible, and makes
it possible to use a single migration where previously two were required.
Pursuant to https://github.com/cakephp/phinx/pull/1151
> Better reversible migrations

- src/Phinx/Db/Adapter/PdoAdapter.php
for me this works fine, seems something got not copied when migrated from PDOAdapter to AbstractAdapter!
Perhaps additional checks are needed but my use cases fork fine again!
> attempt to fix issue #1170

- src/Phinx/Db/Adapter/AbstractAdapter.php
When phinx.yml defines a custom default_migration_table value, this value is not used. "phinxlog" is still used.
.... setSchemaTableName() is never used in the whole project ....
The problem was already present in <0.9 versions but not for PDOAdapter, like if this default_migration_table directive was only available for PDOAdapters. I am using PDOAdapter subclasses so I didn't notice it before. Since 0.9.0 version it is blocking even when using pdo adapters.
> fix : use the default_migration_table yml directive if present

- src/Phinx/Db/Adapter/AbstractAdapter.php
- src/Phinx/Db/Adapter/PdoAdapter.php
Fixing configuration item default_migration_table
> fixing configuration item default_migration_table

- tests/Phinx/Db/Adapter/PdoAdapterTest.php
Adds tests for #1173, #1171, #1167.
Should this maybe be moved to, or have additional integration tests on `EnvironmentTest` class level? `EnvironmentTest::testGetAdapterWithExistingPdoInstance()` seems to have a hint of testing that could have covered #1170, but actually doesn't touch the underlying adapter to check whether it received the expected connection.
Edit: Didn't noticed the whitespace removal... I blame JetBrains.
> Add tests for connection and table name configuration.

- src/Phinx/Db/Adapter/PostgresAdapter.php
- src/Phinx/Db/Adapter/SqlServerAdapter.php
- tests/Phinx/Db/Adapter/PostgresAdapterTest.php
- tests/Phinx/Db/Adapter/SqlServerAdapterTest.php
Per #92, the 'constraint' option was added for naming foreign key constraints. This ability was not implemented in SQL Server or PostgreSQL (but was in SQLite). I've added support and updated the tests accordingly.
This is related to my issue report #1098.
> Support Foreign Key constraint names in SQL Server and PostgreSQL

- src/Phinx/Db/Adapter/AdapterWrapper.php
Due to errors encountered while using getConnection() from migration, I added the missing function in the AdapterWrapper
> Missing function in AdapterWrapper

- src/Phinx/Db/Table.php
Table->setColumns() was not returning $this despite the documentation and thus was not chainable.
It's fixed :-)
> Fix chainability for the setColumns call

- src/Phinx/Db/Adapter/AdapterInterface.php
After https://github.com/cakephp/phinx/pull/1190 broke the build, this attempts to get phpstan green again.
> Fix phpstan error by adding method to interface as annotation.

- src/Phinx/Db/Adapter/AbstractAdapter.php
- tests/Phinx/Db/Adapter/PdoAdapterTestExecChecks.php
Hi. Not sure if I'm missing something, but we've encountered an issue when instantiating a migration environment.
Sample code:
```php
<?php
require __DIR__ . '/vendor/autoload.php';
$manager = new \Phinx\Migration\Manager(
\Phinx\Config\Config::fromPhp(__DIR__ . '/test-config.php'),
new \Symfony\Component\Console\Input\ArrayInput([]),
new \Symfony\Component\Console\Output\NullOutput()
);
class TestSeed extends \Phinx\Seed\AbstractSeed { }
$manager->executeSeed('development', new TestSeed());
```
Where our test configuration is:
```php
<?php
return [
'environments' => [
'development' => [
'name' => 'devdb',
'connection' => new PDO('sqlite::memory:'),
]
]
];
```
We encounter this error:
```
Fatal error: Uncaught Error: Call to a member function hasOption() on null in …
```
> Fatal: hasOption() on null

- .gitattributes
This might be a bit too strict for you, but it's what seems to be non-essential for package installation.
(Sorry for spamming PRs, let me know if you want me to stop 😛)
> Add more files to gitattributes export-ignore

- composer.json
- docs/configuration.rst
- phinx.yml
- tests/Phinx/Config/_files/external_variables.yml
- tests/Phinx/Config/_files/missing_environment_entry.yml
- tests/Phinx/Config/_files/no_default_database_key.yml
- tests/Phinx/Config/_files/seeds.yml
This required adding quotes around `%` in the yaml files. See http://symfony.com/blog/new-in-symfony-3-1-yaml-deprecations for more info on that.
In order to support v4, I tried to find all the places that had `%` unquoted and added them. I'm not sure if there should be another PR to have handled that or not, as I think users should be warned.
Fixes #1223
> Added support for symfony 4 components.

- tests/Phinx/Db/Adapter/SqlServerAdapterTest.php
It looks like that the test just works after removing the return.
The Appveyor job is also green: https://ci.appveyor.com/project/Iandenh/phinx/build/1.0.7
> Fix CS for test

- src/Phinx/Migration/Manager.php
// glob() can return the same file multiple times
// This will cause the migration to fail with a 
// false assumption of duplicate migrations
// http://php.net/manual/en/function.glob.php#110340
> ensure unique file names are returned

- src/Phinx/Db/Adapter/MysqlAdapter.php
- tests/Phinx/Db/Adapter/MysqlAdapterTest.php
_Closed and re-opened from #1165 as I put new commits into my own master branch - use this one instead please_
As per the documentation on [environment configuration](http://docs.phinx.org/en/latest/configuration.html#environments), there should be an option named `collation`. This configuration option doesn't do anything when you set it.
This change will set the default collation of newly created tables in this order:
1. The `collation` option provided in the array of options
2. The `collation` option provided in the environment configuration
3. `utf8_general_ci`
> Apply default collation on tables as per documentation (new #1165)

- tests/Phinx/Config/ConfigMigrationPathsTest.php
- tests/Phinx/Config/ConfigSeedPathsTest.php
- tests/Phinx/Config/ConfigTest.php
- tests/Phinx/Console/Command/CreateTest.php
- tests/Phinx/Db/Adapter/MysqlAdapterTest.php
- tests/Phinx/Db/Adapter/MysqlAdapterUnitTest.php
- tests/Phinx/Db/Adapter/PostgresAdapterTest.php
- tests/Phinx/Db/Adapter/SQLiteAdapterTest.php
- tests/Phinx/Db/Adapter/SqlServerAdapterTest.php
- tests/Phinx/Migration/AbstractMigrationTest.php
- tests/Phinx/Migration/ManagerTest.php
I've refactored some tests, using:
- `assertCount` instead of `count` function;
- `assertInternalType` and `assertNotInternalType` instead of `is_*` functions;
- `assertContains` instead of `in_array` function;
- `assertInstanceOf` instead of `instanceof` operator;
- `assertAttributeEmpty`;
- `assertArrayHasKey` instead of `isset` function;
- `assertStringEqualsFile` when comparing a `string` and a file.
> Refactoring tests

- .travis.yml
- src/Phinx/Migration/Manager.php
- src/Phinx/Seed/AbstractSeed.php
- tests/Phinx/Migration/ManagerTest.php
- tests/Phinx/Migration/_files/seeds/PostSeeder.php
This feature is for ordering seeds execution by seeds dependencies. You can define other seeds which are dependencies for your seed and change seeds execution order automatically.
This feature is useful when you extend phinx manager (for example in unit tests to use in memory database) and do not have possibility execute seeds command from terminal.
Also if you have a lot of seeds it is not convenient to order seeds writing one by one in terminal to run ordered seeds.
Just run `phinx seeds:run` and your seeds will be executed in ordered way.
Use this function to define dependencies:
```
public function getDependencies()
{
return [
'UserSeeder',
'GSeeder',
];
}
```
> Add ordered seeds feature

- box.json
The displayed version number is now being read from composer.json, so this file should be part of the Phar archive as well.
> Include composer.json in Phar archive

- docs/commands.rst
- src/Phinx/Console/Command/Init.php
- tests/Phinx/Console/Command/InitTest.php
With this update Init command can specify custom config names.
All these commands are valid:
```bash
$ vendor/bin/phinx init
$ vendor/bin/phinx init .
$ vendor/bin/phinx init phinx.yml
$ vendor/bin/phinx init ~/Project/custom-config.yml
```
> Enhancing init command

- src/Phinx/Migration/AbstractMigration.php
- src/Phinx/Migration/Manager.php
- src/Phinx/Migration/MigrationInterface.php
- tests/Phinx/Migration/AbstractMigrationTest.php
- tests/Phinx/Migration/Manager/EnvironmentTest.php
- tests/Phinx/Migration/ManagerTest.php
This PR adds functionality requested in #1137.
**Issue**
Sometimes within a migration you may want to have different behavior based on the environment you are in. For example, in my development environment I also stage fixtures in my database i.e add a default user to the development database but not in the testing database.
**Documentation**
- `AbstractMigration` and `MigrationInterface` have been modified with one new methods `::getEnvironment()`.
- The constructor signature of `AbstractMigration` has been modified so the migration gets instantiated with the `$environment` parameter. I don't think this will cause any issues to the end user as I assume users do not override the constructor, they simply extend the migration when creating their own. 
**Example Usage**
```php
use …
```
> Pass Environment Variable Down To Migrations

- src/Phinx/Console/PhinxApplication.php
- tests/Phinx/Console/Command/ListTest.php
Fixes #525 
When running `bin/phinx list` aka `bin/phinx list --format=txt` it would output two version lines when using the text format.
> Phinx by CakePHP - https://phinx.org. version 0.8.1
> Phinx by CakePHP - https://phinx.org. version 0.8.1
> Usage:
>  command [options] [arguments]
>
> Options:
>  -h, --help            Display this help message
>  -q, --quiet           Do not output any message
>  -V, --version         Display this application version
>      --ansi            Force ANSI output
>      --no-ansi         Disable ANSI output
> ...
With this patch it only displays one version line.
The line duplicates because the list command is part of the Symfony Console component which is configured it display the version string for the list command. Phinx is configured to output the …
> remove duplicate version string from list command

- src/Phinx/Db/Adapter/MysqlAdapter.php
- tests/Phinx/Db/Adapter/MysqlAdapterTest.php
When overriding the id field name, the signed option was not working.
In addition, the unit test for signed/unsigned wasn't actually checking
to make sure that option was working.
The fact that I have to loop over the columns and check by name isn't the best, but it seemed to be all I had without writing more code.
> Allow signed named primary_key

- src/Phinx/Db/Table.php
Added `hasIndexByName` method for Table class.
> Added hasIndexByName method for Table class.

- Dockerfile
PHP 5.4 hit EOL over two years ago so it's probably not worth building Docker against it anymore. Moving to PHP 7.0 also has the added advantage of using PHPUnit 6.x development work.
> Move from PHP 5.4 to PHP 7.0 for Docker

- tests/Phinx/Console/Command/ListTest.php
This class throws an exception on PHPUnit 6 currently. All other test classes use the namespaced TestCase already.
> Move List test to use namespaced PHPUnit TestCase

- src/Phinx/Migration/Manager.php
The status command exit code is now  **3** to distinguish it from erroneous situations whose status command exit code was already **1**.
For #806
> Fix status command exit code

- src/Phinx/Console/Command/Migrate.php
- src/Phinx/Console/Command/Rollback.php
- src/Phinx/Console/PhinxApplication.php
- src/Phinx/Migration/Manager.php
- src/Phinx/Migration/Manager/Environment.php
- tests/Phinx/Console/Command/MigrateTest.php
- tests/Phinx/Console/Command/RollbackTest.php
Sort of implements what #841 is asking fo with a different implementation than #266 (more inline with how Django's migration tool works). Though, this doesn't add a 'fake-initial' command, you'd just have to use fake with the appropriate options to just run it for your initial migration if you only wanted to fake that.
Both migrate and rollback accept a `--fake` flag that when used will mark any specified migrations/rollbacks as having been done, but won't actually run the up/down/change methods for the migration.
Usage:
```
bin/phinx migrate --help                                                                 [11:30:28]
Usage:
migrate [options]
Options:
-c, --configuration=CONFIGURATION  The configuration file to load
-p, --parser=PARSER                Parser used to read the config …
```
> Add --fake flag to migrate and rollback commands

- src/Phinx/Db/Adapter/SQLiteAdapter.php
- tests/Phinx/Db/Adapter/SQLiteAdapterTest.php
Modify SQLiteAdapter to use the transaction methods provided by PDO
rather than directly executing transaction commands against the connection.
This allows getConnection()->inTransaction() to return the proper value.
Fixes #1312
> Fix SQLite transaction handling

- src/Phinx/Db/Adapter/MysqlAdapter.php
currently a specified id field is not able to be unsigned.
> allow custom id field to be unsigned

- src/Phinx/Db/Adapter/SQLiteAdapter.php
- tests/Phinx/Db/Adapter/SQLiteAdapterTest.php
Modify createTable to remove any identity columns from the primary_key
list to ensure that the SQLite adapter doesn't attempt to define the
primary key multiple times.
Fixes #1297
> Fix SQLite & MySQL identity definition incompatibility

- docs/configuration.rst
- src/Phinx/Migration/Manager/Environment.php
- tests/Phinx/Migration/Manager/EnvironmentTest.php
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixes issues? | #646
| Agree to license? | yes
| Documentation? | yes
Adds support for providing database connection details as a DSN string (such as with Symfony 4).
It's a feature that I want, so I wrote it - would love feedback on it!
I'm not sure if its the correct way of doing things, I just dived headfirst into it.
```yaml
environments:
default_migration_table: phinxlog
default_database: development
development:
dsn: mysql://appuser:supersecretpassword@localhost:3306/mydb?charset=utf8
```
That regex string can be a little unwieldy, so here's a handy diagram to help anyone trying to decipher it!
> Add Support for Database-Agnostic DSN

- docker-compose.yml
- src/Phinx/Db/Adapter/MysqlAdapter.php
- src/Phinx/Db/Adapter/PdoAdapter.php
- tests/Phinx/Db/Adapter/MysqlAdapterTest.php
- tests/Phinx/Db/Adapter/MysqlAdapterUnitTest.php
Implements #1003 and #1301, allowing someone to specify a limit for time, timestamp, and datetime types. Trying to use this on older versions of mysql (< 5.6.3) will throw a PDO exception. 
For local testing, I bumped the docker-compose to use mysql 5.6 instead of 5.5.
I've added a check on mysql version for the related tests so as to skip them on those MySQL versions (and added the necessary function to get database version for the PDOAdapter using http://php.net/manual/en/pdo.getattribute.php).
> Add ability to specify limit for timestamp/date/time columns for mysql

- src/Phinx/Db/Adapter/PostgresAdapter.php
- tests/Phinx/Db/Adapter/PostgresAdapterTest.php
This allows specifying a precision value for `time` and `timestamp` in PostgreSQL, which gets mapped to the `datetime_precision` attribute in the `information_schema`:
```
$this->table('table1')->addColumn('timestamp1', 'timestamp', array(
'precision' => 0
))
```
> Precision for PostgreSQL time types

- src/Phinx/Db/Adapter/PostgresAdapter.php
This is a follow-up to #1175 which apparently started breaking tests. I think this might be enough to fix the issue.
> Fix tests breaking due to double column type check in PostgresAdapter

- src/Phinx/Migration/Manager.php
Adds a 'missing_count' (for number of missing migrations) and 'total_count' (for total number, including missing, migrations). Pending migrations only counts migrations that exist and are down.
Fixes #1014
Example outputs:
```
Status  Migration ID    [Started          ]  Finished             Migration Name
----------------------------------------------------------------------------------
up  20180302192357  2018-05-10 21:26:28  2018-05-10 21:26:28  Test  ** MISSING **
down  20180510210702                                            TestMe
{"pending_count":1,"missing_count":1,"total_count":2,"migrations":{"20180510210702":{},"20180510210703":{"migration_status":"down","migration_id":"20180510210702","migration_name":"TestMe"}}}
```
```
Status  Migration ID    [Started          ]  Finished …
```
> Make counts in JSON output of status more meaningful

- src/Phinx/Db/Adapter/AbstractAdapter.php
- src/Phinx/Db/Adapter/PostgresAdapter.php
- tests/Phinx/Db/Adapter/PostgresAdapterTest.php
Added full support of different schemas for Postgres (#828). Use-case:
```php
$this->getAdapter()->createSchema('schema1');
if (!$this->hasTable('schema1.example1')) {
$table = $this->table('schema1.example1');
$table
->addColumn('column1', 'integer')
->save();
}
$this->getAdapter()->createSchema('schema2');
if (!$this->hasTable('schema2.example2')) {
$table = $this->table('schema2.example2');
$table
->addColumn('column2', 'integer')
->save();
$table
->addForeignKey('column2', 'schema1.example1', 'id')
->save();
}
```
Instead of now:
```php
$this->getAdapter()->createSchema('schema1');
$this->getAdapter()->setOptions(array_replace($this->getAdapter()->getOptions(), ['schema' => 'schema1']));
if (!$this->hasTable('example1')) {
$table = $this->table('example1');
$table …
```
> Added full support of different schemas for Postgres.

- docs/migrations.rst
- src/Phinx/Db/Table.php
- tests/Phinx/Db/TableTest.php
This PR adds a third argument to `Db\Table::addTimestamps` which lets the developer control whether the timestamp columns being added will retain the timezone information. I also fixed the indentation being all over the place in that method.
This is the cleanest solution I could think of to add support for changing this value, but I'm open to feedback.
> Add option to addTimestamps with timezone column types

- src/Phinx/Console/PhinxApplication.php
It's apparant that this section of code was trying to always print an
extended version string because Symfony console only does it for certain
tasks by default.
Previously:
$ ./bin/phinx |head -3
```
Phinx by CakePHP - https://phinx.org. 0.10.0
Usage:
```
$ ./bin/phinx -h|head -3
```
Description:
Lists commands
```
$ ./bin/phinx help|head -3
```
Phinx by CakePHP - https://phinx.org. 0.10.0
Description:
```
$ ./bin/phinx list|head -3
```
Phinx by CakePHP - https://phinx.org. 0.10.0
Usage:
```
After patch:
$ ./bin/phinx |head -3
```
Phinx by CakePHP - https://phinx.org. 0.10.0
Usage:
```
$ ./bin/phinx -h|head -3
```
Phinx by CakePHP - https://phinx.org. 0.10.0
Description:
```
$ ./bin/phinx help|head -3
```
Phinx by CakePHP - https://phinx.org. 0.10.0
Description:
```
$ ./bin/phinx …
> Fix for always printing extended version info

- docs/migrations.rst
After 0.10, we the `dropForeignKey` and `dropTable` methods are lazy, like all other methods. This reflects that change in the docs
fixes #1367
> Updating information about using dropTable and dropForeignKey

- src/Phinx/Migration/AbstractMigration.php
There is little point of having yet another way of dropping a table. Migrations should happen only through the Table class.
refs #1367
> Making dropTable work again and deprecating it

- docs/migrations.rst
- docs/seeding.rst
- src/Phinx/Migration/AbstractMigration.php
- src/Phinx/Migration/MigrationInterface.php
- tests/Phinx/Migration/AbstractMigrationTest.php
- tests/Phinx/Migration/_files/reversiblemigrations/20170824134305_direction_aware_reversible_up.php
Building off https://github.com/cakephp/phinx/issues/1367#issuecomment-396966171 and the previous commits of today on dropTable.
This adds a deprecated tag on insert() as well (to match dropTable's) and has both methods trigger a `E_USER_DEPRECATED` warning so as to be explicit about this going away (and to follow PHP's model of having deprecated functions issuing said warning).
I also added version information to the deprecated tag to show when it was deprecated. You may also want to add info when the functions will be removed.
The releases page probably should also be updated to reflect that these two functions are deprecated.
> Add deprecated warning to insert() and trigger_error on both

- docs/configuration.rst
- src/Phinx/Db/Adapter/SQLiteAdapter.php
The file extension was hardcoded to ".sqlite3", this allows for
overriding that in the phinx.yml options for database adapters.
Partially fixes #1245
> Allow file suffix db adapter option for sqlite

- src/Phinx/Migration/AbstractMigration.php
- src/Phinx/Migration/Manager.php
- src/Phinx/Migration/MigrationInterface.php
The presence of the change() method ignores individual up() or down()
methods, but there is no warning to end users.  The preFlightCheck for
AbstractMigration allows the opportunity to warn about potential
conflicts.
Fixes #1329
> Warn when up or down will be ignored

- src/Phinx/Migration/AbstractMigration.php
- src/Phinx/Migration/MigrationInterface.php
- tests/Phinx/Migration/AbstractMigrationTest.php
With the change from #1375, all migrations that only use change throw a warning regardless of whether or not the migration file had an up/down function. This is because those functions always exist due to the AbstractMigration file. Given that the change function is not in the AbstractMigration (or MigrationInterface), to keep things consistent (and not show this warning always), can just remove the functions.
> Remove up/down functions from abstract

- src/Phinx/Db/Adapter/PdoAdapter.php
- tests/Phinx/Db/Adapter/PostgresAdapterTest.php
Postgresql - seeding boolean column gets: Invalid text representation for false value
https://github.com/cakephp/phinx/issues/1038
> ISSUE-1038 Postgresql - seeding boolean column

- src/Phinx/Db/Table/Column.php
Precision and scale usually used together. Add setter to set both parameters at once, so they look like in SQL datatype `DECIMAL(11, 3)`. This also helps prevent from mixing precision and scale.
> Add setPrecisionAndScale

- src/Phinx/Db/Adapter/MysqlAdapter.php
- tests/Phinx/Db/Adapter/MysqlAdapterTest.php
SQLSTATE[HY000]: General error: 1795 InnoDB presently supports one FULLTEXT index creation at a time
Ref #1392
> Add FULLTEXT indexes on MySQL one at a time

- src/Phinx/Db/Adapter/PdoAdapter.php
- tests/Phinx/Db/Adapter/MysqlAdapterTest.php
- tests/Phinx/Db/Adapter/PostgresAdapterTest.php
`$table->addColumn('column1', 'boolean', ['default' => null, 'null' => true])` was added as `column1 tinyint(1) NOT NULL DEFAULT 0`
> Boolean fields couldn't have default NULL

- docs/migrations.rst
The addForeignKey() example doesn't work with MySQL because it uses the "SET NULL" option, but the field is not nullable.
> Fix the addForeignKey() example.

- src/Phinx/Migration/Manager.php
> Do not output all migrations in the -vvv output when running migrations every single time.

- src/Phinx/Db/Table.php
- src/Phinx/Migration/AbstractMigration.php
- src/Phinx/Migration/Manager.php
- src/Phinx/Migration/MigrationInterface.php
- tests/Phinx/Db/Adapter/MysqlAdapterTest.php
- tests/Phinx/Db/TableTest.php
- tests/Phinx/Migration/AbstractMigrationTest.php
Since the mechanics of migrations changed lately to require a call to save() some of my old migrations did not actually do anything after upgrading to 0.10 but I did not notice it until my tests started failing. Finding the issues was also fairly laborous.
To make it easier I wrote a checker function that throws an exception when there are unsaved changes in a migration when the migration completes. I cannot think of any valid use case where it is not an error and therefore did not provide a way to skip the check.
> Throw an error if there are pending changes when migration completes

- docs/migrations.rst
Hey,
as far as I know, is it not possible to create migrations with `php vendor/bin/phinx create MyNewMigration` but with `vendor/bin/phinx create MyNewMigration`
#752
> Creating new Migration - without php in command // Update Docs

- docs/migrations.rst
A missing backtick was messing up the formatting at one point.
> Fix formatting in Foreign Keys section

- src/Phinx/Db/Table.php
Phinx\Db\Action\DropColumn doesn't exist, remove the use statement in Phinx\Db\Table
> remove unused use statement for Phinx\Db\Action\DropColumn;

- src/Phinx/Db/Adapter/MysqlAdapter.php
- src/Phinx/Db/Adapter/PostgresAdapter.php
- src/Phinx/Db/Adapter/SQLiteAdapter.php
- src/Phinx/Db/Adapter/SqlServerAdapter.php
- src/Phinx/Db/Adapter/UnsupportedColumnTypeException.php
- tests/Phinx/Db/Adapter/MysqlAdapterTest.php
- tests/Phinx/Db/Adapter/PostgresAdapterTest.php
- tests/Phinx/Db/Adapter/SQLiteAdapterTest.php
- tests/Phinx/Db/Adapter/SqlServerAdapterTest.php
This is an alternative for PR #1432 and adds support for all relevant DBMS adapters.
> Return Literal when column is not a Phinx type

- docs/commands.rst
In #806 the exit code for a down migration changed from **1** to **3**.  This PR corrects the documentation.
> Correct docs for the status exit codes.

- src/Phinx/Db/Adapter/SQLiteAdapter.php
Copy of: cakephp#1441 just made separate branch so other fixes wouldn't conflict comparing forked repo..
Quoting column name when doing check command for example if doing enum in sqlite and column name is reserved words such as "limit"
> Quote column names when running CHECK command

- src/Phinx/Db/Adapter/SQLiteAdapter.php
Problem exists when we want to change primary key of non-integer column. Match doesn't work so no primary key added. With this change if "creation" SQL is not with INTEGER then we parse all data from column, for example my_primary VARCHAR(100) NOT NULL will be changed to my_primary VARCHAR(100) PRIMARY KEY. (now it does not preg_match, would preg_match my_primary VARCHAR NOT NULL and change to INTEGER AUTOINCREMENT..)
Pseudo-reproduction:
1st migration:
$this->table('sometable', ['primary_key' => 'abc']);
2nd:
$this->table('sometable')->changePrimaryKey('dfg'); <- dfg is varchar
This is backwards compatible change if integers is passed without limitations and autoincrement is still there (probably it was intended?)
> Allow primary key change on non-integer columns

- Dockerfile
- composer.json
* when running phpunit in docker, it asks for php 7.1, so changed php version in dockerfile to 7.1
* after rebuilding the container, phpunit gives warnings about column counts, which appear in phpunit 7.*, so added <7.0 to phpunit version spec
* after composer update, everything works correctly
> Update Dockerfile to use php:7.1 and update composer dependencies

- docs/configuration.rst
- src/Phinx/Config/Config.php
- src/Phinx/Config/ConfigInterface.php
- src/Phinx/Console/Command/AbstractCommand.php
- src/Phinx/Util/Util.php
This fixes #611. The implementation is a bit different than what is described in the issue. This is global for all environments and run before any command but after config is parsed.
I've added under the configuration paths a new `bootstrap` path which would be a path to a php file to run before commands run. Similar to how phpunit can define a bootstrap file.
```yaml
#phinx.yaml 
paths:
bootstrap: 'phinx-bootstrap.php'
```
This configuration option is checked and if found will simply do a php `include_once` on the file. Wasn't sure how you'd want to handle error handling. So I just have it blow up if anything goes wrong. Let me know if you have better suggestions on what to show users if the bootstrap is borked.
I'm happy to add the appropriate unit tests around the code just wanted to …
> Add feature to be able to define a boostrap script

- src/Phinx/Console/Command/Migrate.php
As in #963 described, the bash currently gets the status code 0 if the migration fails. With this PR it will get the status code 1.
> Add Exit Status 1 on Exception

- src/Phinx/Db/Table.php
- tests/Phinx/Db/TableTest.php
Hello,
I found a small bug. Running:
```
$this->table('my_table')->insert([])->save();
```
will insert a row when it should not.
The above code is stupid but in my case the array passed to the insert function is a variable. I'm creating a migration to move data from old tables to new ones. In this migration, I loop on all rows of old tables, and get some column to feed into the new tables. When running against an empty database (schema only, no rows), this migration should loop on an empty array and do nothing.
Instead, I can find a new line for each table in the database, with each table id being a single space, and the other columns empty or with default values.
As a workaround I have to check if the array is empty before calling or not the `save()` method.
Thank you for your thoughts …
> Prevent data insertion when passing an empty array

- src/Phinx/Db/Adapter/MysqlAdapter.php
- src/Phinx/Db/Adapter/PostgresAdapter.php
- src/Phinx/Db/Adapter/SQLiteAdapter.php
- src/Phinx/Db/Adapter/SqlServerAdapter.php
Makes it so that regardless if you're setting `id` or not, it'll use the same if block of code, instead of previously having two identical blocks except one used the string 'id' and the other `$options['id']`
> Simplify logic around default primary key name when creating table

- src/Phinx/Db/Adapter/SQLiteAdapter.php
Hello I found this bug with the SQLite Adapter it doesn't respect a limit on CHAR typed columns
Without the fix performing a migration like this
```
$table = $this->table('my_table', ['id' => false]);
$table->addColumn('char_col', 'char', ['limit' => 32])->create();
```
Results in
```
sqlite> pragma table_info(my_table);
0|char_col|CHAR|0||0
```
After fix the same migration results in
```
0|char_col|CHAR(32)|0||0
```
> SQLite Adapter does not respect LIMIT on CHAR typed columns

- docs/seeding.rst
It wasn't obvious that dependencies won't be considered when running specific seed classes (-s)
> Update documentation on seeding

- docs/migrations.rst
#1248 added support for the MySQL column type `bit`,
but the type was not yet mentioned in the docs.
In addition, this PR aligns the currently inconsistent sections *Working With Tables* and *Working With Columns* w.r.t. the columns supported by the MySQL and Postgres adapter.
> docs: add MySQL `bit` type

- box.json
With regards to #1520:
Considering humbug/box (https://github.com/humbug/box) is now the actively maintained app for building phars, I updated the box.json configuration so that working phars can be generated.  
The existing box.json was not working at all as humbug/box excludes composer.json from the root unless you explicitly set a flag to tell it not to.
> Fix box configuration to work with humbug/box

- docs/migrations.rst
As introduced with #1493 und released with 0.10.7 using `double` is possible.
This PR adds it to the valid column types list.
> Add double to valid column types

- docs/seeding.rst
Avoid error: Base table or view already exists: 1050 Table <table_name> already exists
> Docs about seed: Call to save() method replaced for saveData()

- src/Phinx/Db/Adapter/PdoAdapter.php
- src/Phinx/Db/Adapter/SQLiteAdapter.php
- tests/Phinx/Db/Adapter/SQLiteAdapterTest.php
Enhances `SQLiteAdapter::hasTable()` so that it can find tables in any already-attached database, including temporary tables when explicitly asked for. 
Also fixes a quoting issue the original implementation had: table names containing `'` would previously cause the method to error out. This required changing the `PdoAdapter::quoteValue()` method visibility to `protected`.
> Fix for issue #1535

- src/Phinx/Db/Adapter/PdoAdapter.php
- src/Phinx/Db/Adapter/SQLiteAdapter.php
- tests/Phinx/Db/Adapter/SQLiteAdapterTest.php
A second attempt at fixing `SQLiteAdapter::hasTable()`.
Notably, it is able to find tables in any schema rather than only main, and is also able to find tables when the main schema is explicitly specified.
Like [SQLite itself](https://sqlite.org/lang_naming.html), if no schema is specified it will search all schemata until the table is found. This is unlike the other adapters, but is internally consistent.
This fixes #1535.
> New hasTable implementation for SQLite

- src/Phinx/Db/Adapter/SQLiteAdapter.php
- tests/Phinx/Db/Adapter/SQLiteAdapterTest.php
Enhances `SQLiteAdapter::hasIndex()` and `SQLiteAdapter::hasIndexByName()` and related functionality in the following ways:
- Correctly enumerates a tables indices when searching for a match
- Matches named indices case-insensitively
- Matches indices by column only if _all_ columns of the index are present in the query array
- Adjusts the `Table::removeIndex()` and `Table::removeIndexByName()` handlers so that they too benefit from these improvements
I suspect there are also bugs in table re-creation related to indices, but I'm trying to avoid digging into the alteration functionality for now.
Fixes #1544.
> Fixes to SQLite index handling

- src/Phinx/Db/Adapter/SQLiteAdapter.php
- tests/Phinx/Db/Adapter/SQLiteAdapterTest.php
Corrected implementations of `SQLiteAdapter::hasPrimaryKey()` and `SQLiteAdapter::hasForeignKey()`. They were changed in the following ways:
- Avoids haphazard SQL scraping
- Reports correctly on composite primary keys
- Reports correctly on composite foreign keys
- Reports correctly on subsets of composite keys
- Fully case-insensitive
- Fails noisily when a named constraint is queried
Fixes #1538 and  fixes #1539.
> New hasPrimaryKey and hasForeignKey implementations for SQLite

- src/Phinx/Db/Adapter/SQLiteAdapter.php
- src/Phinx/Util/Expression.php
- tests/Phinx/Db/Adapter/SQLiteAdapterTest.php
- tests/Phinx/Util/ExpressionTest.php
This change constitutes a new implementation of `SQLiteAdapter::getColumns()`. The method itself is not significantly changed, but it now calls out to two new methods: one which correctly identify a table's identity column (if any), and another which correctly interprets default-value expressions. Specifically, the following expressions are recognized and converted to applicable PHP types:
- String literals
- Integers and hexadecimal numbers
- Floats
- `NULL`
- `CURRENT_DATE`, `CURRENT_TIME`, and `CURRENT_TIMESTAMP`
- `TRUE` and `FALSE` (for SQLite 3.24 and later)
Anything else (including blob literals, for now) is wrapped in an instance of the new `Expression` class, a companion to the existing `Literal` class.
~Note that the existing tests for `getColumns()` have been retained as they …
> New implementation of getColumns for SQLite

- src/Phinx/Db/Adapter/SQLiteAdapter.php
- tests/Phinx/Db/Adapter/SQLiteAdapterTest.php
Pursuant to #1474 and #1555, this patch applies an equivalent fix to `SQLiteAdapter::truncateTable()`.
The diff is a bit confused because most of `hasTable()` has been moved to a more diligent `resolveTable()` method which can be used to determine which schema a table is actually found in. This is necessary to delete from the correct `sqlite_sequence` table when no schema is specified.
>  Fix table truncation for SQLite

- docs/commands.rst
- src/Phinx/Console/Command/Breakpoint.php
- src/Phinx/Db/Adapter/AdapterInterface.php
- src/Phinx/Db/Adapter/AdapterWrapper.php
- src/Phinx/Db/Adapter/PdoAdapter.php
- src/Phinx/Migration/Manager.php
- tests/Phinx/Console/Command/BreakpointTest.php
- tests/Phinx/Migration/ManagerTest.php
This enhances the current breakpoint feature and provides greater control
over the state of a breakpoint, without the need to have any prior
knowledge of the state of the breakpoints.
> Introduce `--set` and `--unset` options for breakpoints.

- .travis.yml
- appveyor.yml
- composer.json
- src/Phinx/Db/Adapter/MysqlAdapter.php
- src/Phinx/Db/Adapter/PostgresAdapter.php
- src/Phinx/Db/Adapter/SQLiteAdapter.php
- src/Phinx/Db/Adapter/SqlServerAdapter.php
There aren't package splits yet for 4.x-dev so we will have to pull in the entire thing. This will enable cakephp/migrations to make progress, and update travis to no longer test against PHP 5 or EOL PHP 7.
> Add development version of CakePHP

- src/Phinx/Db/Adapter/AbstractAdapter.php
- src/Phinx/Db/Adapter/MysqlAdapter.php
- src/Phinx/Db/Adapter/PostgresAdapter.php
- src/Phinx/Db/Adapter/SQLiteAdapter.php
- src/Phinx/Db/Adapter/SqlServerAdapter.php
- tests/Phinx/Db/Adapter/MysqlAdapterTest.php
- tests/Phinx/Db/Adapter/PostgresAdapterTest.php
- tests/Phinx/Db/Adapter/SQLiteAdapterTest.php
- tests/Phinx/Db/Adapter/SqlServerAdapterTest.php
Fixes #1569 where because running under dry-run meant that the table was never actually created subsequent checks for existence of the table would fail, and an extra invalid `CREATE TABLE` statement would end up getting inserted into the dry-run log.
I'm not 100% satisfied with how this looks, but unsure of how might improve things and reduce the amount of copy/paste of things. It'll also still fail in the case where someone would directly call `execute()` with a create/drop/rename query.
> Cache names of created tables for exists check

- src/Phinx/Db/Adapter/MysqlAdapter.php
- src/Phinx/Db/Adapter/PdoAdapter.php
- src/Phinx/Db/Adapter/PostgresAdapter.php
- src/Phinx/Db/Adapter/SqlServerAdapter.php
- tests/Phinx/Db/Adapter/MysqlAdapterTest.php
- tests/Phinx/Db/Adapter/PdoAdapterTest.php
- tests/Phinx/Db/Adapter/PostgresAdapterTest.php
- tests/Phinx/Db/Adapter/SqlServerAdapterTest.php
Fixes #1567. 
Using `--dry-run` was lacking the semi-colon at the end of any of the commands for transactions for MySQL, PostgreSQL, and SQLServer. This PR adds the missing semi-colons, and add tests to ensure proper behavior.
> Add semicolon for transaction sql lines for --dry-run

- tests/Phinx/Migration/ManagerTest.php
Fixes #1574.
The test now properly relies on a postgresql database being up and running, instead of using mysql. I'm not sure if it might be desired to replicate this test for mysql as well given that was what it has been using for some time.
> Fix testPostgresFullMigration to actually use postgres database for test

- src/Phinx/Console/Command/Breakpoint.php
- src/Phinx/Console/Command/Create.php
- src/Phinx/Console/Command/Init.php
- src/Phinx/Console/Command/Migrate.php
- src/Phinx/Console/Command/Rollback.php
- src/Phinx/Console/Command/SeedCreate.php
- src/Phinx/Console/Command/SeedRun.php
- src/Phinx/Console/Command/Status.php
- src/Phinx/Console/Command/Test.php
- src/Phinx/Console/PhinxApplication.php
- tests/Phinx/Console/Command/BreakpointTest.php
- tests/Phinx/Console/Command/CreateTest.php
- tests/Phinx/Console/Command/InitTest.php
- tests/Phinx/Console/Command/MigrateTest.php
- tests/Phinx/Console/Command/RollbackTest.php
- tests/Phinx/Console/Command/SeedCreateTest.php
- tests/Phinx/Console/Command/SeedRunTest.php
- tests/Phinx/Console/Command/StatusTest.php
_Fix for #1585_
Symfony's Command require their name to return a string and don't allow a null
value, however in Phinx, in order to allow users to override the command names,
Commands in PhinxApplication are constructed without a name, and then in the
Command's configure method, a default name is set if getName is null.
Up until now, it worked as Symfony didn't enforce return types (types were
simply declared in PHPdoc), however for its version 5 Symfony plans to enforce
them, hence breaking Phinx commands.
To fix it, a COMMAND_NAME class constant has been introduced, and
PhinxApplication uses it when instantiating Commands.
> Fixed Command names

- composer.json
- phpunit.xml.dist
- tests/Phinx/Migration/AbstractMigrationTest.php
PR to overrule #1543. PHPUnit 8+ cannot be used unless this library goes PHP 7.1+ only as typehints were added across the codebase, most notably the `setUp` and `tearDown` functions got the `void` typehint. 
On the other PR, you will probably need to tell dependabot `@dependabot ignore this dependency` until such a time as phinx is 7.1+.
> Update phpunit/phpunit requirement from >=5.7,<7.0 to >=5.7,<8.0

- composer.json
- src/Phinx/Console/Command/Breakpoint.php
- src/Phinx/Console/Command/Create.php
- src/Phinx/Console/Command/Init.php
- src/Phinx/Console/Command/Migrate.php
- src/Phinx/Console/Command/Rollback.php
- src/Phinx/Console/Command/SeedCreate.php
- src/Phinx/Console/Command/SeedRun.php
- src/Phinx/Console/Command/Status.php
- src/Phinx/Console/Command/Test.php
- src/Phinx/Console/PhinxApplication.php
- tests/Phinx/Console/Command/BreakpointTest.php
- tests/Phinx/Console/Command/CreateTest.php
- tests/Phinx/Console/Command/InitTest.php
- tests/Phinx/Console/Command/MigrateTest.php
- tests/Phinx/Console/Command/RollbackTest.php
- tests/Phinx/Console/Command/SeedCreateTest.php
- tests/Phinx/Console/Command/SeedRunTest.php
- tests/Phinx/Console/Command/StatusTest.php
From the comments in #1588, namely:
> Another solution could be to use the `$defaultName` static property, which serves a similar need directly in `symfony/console`
_Originally posted by @stof in https://github.com/cakephp/phinx/pull/1588#issuecomment-525334319_
> @stof do you like to open a PR with using `defaultName` ?
> it is good idea
_Originally posted by @saeideng in https://github.com/cakephp/phinx/pull/1588#issuecomment-525458265_
This uses the `$defaultName` static variable available in Symfony\Console (https://github.com/symfony/console/blob/6b101586a5938f1a5958ef0d6ca598755b6d6ea8/Command/Command.php#L32-L35) to set a name for the command to be used if a different name is not passed in the constructor.
Note, this does requiring bumping the dependencies for symfony/console to …
> Use existing protected static defaultName for console commands

- .travis.yml
- composer.json
Adds a new job that runs `--prefer-lowest` for the lowest tested version of PHP (`5.6`) to ensure correctness of the library. Added per this comment https://github.com/cakephp/phinx/pull/1591#issuecomment-525316234 and trying to follow advice set in https://www.dereuromark.de/2019/01/04/test-composer-dependencies-with-prefer-lowest/ on adding it.
Fixes #1587
> add --prefer-lowest flag to composer install for travis-ci

- src/Phinx/Util/Util.php
Fixes a batch of the errors in https://travis-ci.org/cakephp/phinx/jobs/578364719.
While implode allows either ordering currently for historical reasons, PHP 7.4 has now deprecated the old syntax.
> Fix ordering of arguments to implode

- src/Phinx/Migration/Manager.php
- tests/Phinx/Migration/ManagerTest.php
Closes #1612, unblocks #1600.
The output for the `status` command is now the same on both 32-bit and 64-bit PHP, as a list of migrations instead of a map with random keys.
> Make same output for migrations value of status JSON for 32 and 64 bit PHP

- appveyor.yml
- src/Phinx/Migration/Manager.php
- tests/Phinx/Migration/ManagerTest.php
Sort of fixes #962
If using `--format json` for `phinx status`, it will print out just the JSON object and not the full status table as well.
Before:
```
Phinx by CakePHP - https://phinx.org. 0.11.1
using config file ./phinx.yml
using config parser yaml
using migration paths
- /Users/mpeveler/Work/Github/phinx/db/migrations
using seed paths
warning no environment specified, defaulting to: production
using format json
ordering by creation time
Status  [Migration ID]  Started              Finished             Migration Name
----------------------------------------------------------------------------------
up  20190828175258  2019-08-28 17:55:41  2019-08-28 17:55:41  TestMigration
{"pending_count":0,"missing_count":0,"total_count":1,"migrations":{"20190828175259":{"migration_status":"up","mig …
```
> Do not print out status table when specifying --format json

- src/Phinx/Console/Command/Breakpoint.php
- src/Phinx/Console/Command/Migrate.php
- src/Phinx/Console/Command/Rollback.php
- src/Phinx/Console/Command/SeedRun.php
- src/Phinx/Console/Command/Status.php
- tests/Phinx/Console/Command/BreakpointTest.php
- tests/Phinx/Console/Command/MigrateTest.php
- tests/Phinx/Console/Command/RollbackTest.php
- tests/Phinx/Console/Command/SeedRunTest.php
- tests/Phinx/Console/Command/StatusTest.php
Right now, if you pass an invalid environment to the commands, it is inconsistent what will happen:
Throws `\InvalidArgumentException` from within the Manager.php:
* breakpoint
* rollback
* status (exception is printed after the first line of the table is printed)
Prints `<error>Could not determine database name! Please specify a database name in your config file.</error>`:
* migrate
* seed:run
The first is probably not quite the right thing as the bad environment could come from the command line or from the phinx yml file itself, and the second case (database name) is just misleading.
This unifies things to always print out `<error>The environment "%s" does not exist</error>` message (same as the `\InvalidArgumentException`, but without the exception) in all cases, as well as before …
> Print error when using invalid environment

- tests/Phinx/Migration/ManagerTest.php
Relatively inconsequential test code documentation fix, but without the fix my editor complains that there's an error in `ManagerTest` where `$config` is passed to something that expects a `ConfigInterface` type.
> fix phpdoc type for ManagerTest::testPrintStatusMethodVersionOrderHeader

- docker-compose.yml
Exposes the ports for the databases that are spun up by the docker-compose file. This makes using the docker-compose file possible without also having to be forced into using it solely within the phinx application. I personally would prefer to use my host terminal and its tools (e.g. zsh, usql) for working, not a plain Debian based system.
> Expose ports for databases in docker-compose

- src/Phinx/Config/Config.php
- src/Phinx/Config/ConfigInterface.php
- src/Phinx/Console/Command/ListAliases.php
- src/Phinx/Console/PhinxApplication.php
- tests/Phinx/Config/_files/seeds_with_aliases.yml
- tests/Phinx/Config/_files/valid_config_with_aliases.json
- tests/Phinx/Config/_files/valid_config_with_aliases.php
- tests/Phinx/Console/Command/ListAliasesTest.php
For those using migration template generators, the use of aliases provides a nice way to keep the names short, rather than providing full class names.
But the list of aliases and what they are aliasing is only available within the config file. Which is fine. 
This command simply lists the aliases and the aliased class.
> Introduce new command to list migration template creation aliases.

- src/Phinx/Db/Adapter/PostgresAdapter.php
fixes PDOException: SQLSTATE[42601]: Syntax error: 7 ERROR:  type modifier is not allowed for type "text"
> postgresql does not allow limit parameter for type text

- src/Phinx/Db/Adapter/MysqlAdapter.php
- tests/Phinx/Db/Adapter/MysqlAdapterTest.php
Closes #1625 
It was not possible to make `smallinteger` unsigned in mysql. This fixes it, while adding tests for ensuring that the smallinteger and biginteger types are signable/unsignable.
I also verified using the following migration:
```
<?php
use Phinx\Migration\AbstractMigration;
class FirstMigration extends AbstractMigration
{
public function change()
{
$this->table('orders')
->addColumn('column1', 'boolean')
->addColumn('column2', 'boolean', ['signed' => false])
->addColumn('column3', 'smallinteger')
->addColumn('column4', 'smallinteger', ['signed' => false])
->addColumn('column5', 'integer')
->addColumn('column6', 'integer', ['signed' => false])
->addColumn('column7', 'biginteger')
->addColumn('column8', 'biginteger', ['signed' => false])
->create();
}
}
```
Where pre-fix, …
> Fix using unsigned with smallint for mysql

- docs/commands.rst
Adds documentation per @dereuromark's request in #1628. Uses a combination of https://github.com/cakephp/phinx/issues/1365#issuecomment-396245197 and https://symfony.com/doc/current/console/calling_commands.html to explain how to do it so that it's better highlighted.
> Add block on executing Phinx inside another symfony console app

- src/Phinx/Migration/Manager.php
- src/Phinx/Util/Util.php
- tests/Phinx/Util/UtilTest.php
`Manager::getMigrationFiles` and `Manager::getSeedFiles` did more or less the same with just a deviation of the paths used. Given that the functions are marked as just `protected` instead of `private`, I elected to not remove them in-case they're being modified by downstream consumers of phinx.
> Remove duplication of get[Migration|Seed]Files functions

- .gitattributes
- .gitignore
- composer.json
- src/Phinx/Console/PhinxApplication.php
We need to remove this version thingie
Without tooling/automation releasing otherwise is always by design error prone
> remove version

- docs/migrations.rst
Closes #1391
Adds `save()` call after calling `removeIndex` and `removeIndexByName` as it's necessary to do that now.
It should be noted that on https://book.cakephp.org/4/en/phinx/migrations.html#working-with-indexes, they already had the `save()` call, which makes me wonder where it's pulling its sources from for its docs as I could not find any branch in the repo that had this.
> Add save() call after removeIndex in docs

- .travis.yml
PHP 7.4 got released on Nov 28, and so it's no longer necessary to test against the snapshot on Travis.
The next version (8.0) is currently not possible to use with PHPUnit so cannot add `nightly` or `8.0snapshot` for future testing.
> Update travis to test against 7.4 stable

- docs/install.rst
The composer.json file specifies a minimum dependency of PHP 5.6:
https://github.com/cakephp/phinx/blob/688f40619fd00e79cbafcfae0069786ece26ecea/composer.json#L27-L28
> Fix minimum required version of PHP in install docs

- composer.json
cakephp/core and cakephp/datasource are sub-dependencies of cakephp/database and so not necessary to include directly, though does require a bump in version of the cakephp/database (see https://travis-ci.org/MasterOdin/phinx/jobs/626553916 for error that happens otherwise).
> Remove non-necessary cakephp dependencies

- src/Phinx/Console/Command/AbstractCommand.php
- src/Phinx/Console/Command/Breakpoint.php
- src/Phinx/Console/Command/Create.php
- src/Phinx/Console/Command/Init.php
- src/Phinx/Console/Command/ListAliases.php
- src/Phinx/Console/Command/Migrate.php
- src/Phinx/Console/Command/Rollback.php
- src/Phinx/Console/Command/SeedCreate.php
- src/Phinx/Console/Command/SeedRun.php
- src/Phinx/Console/Command/Status.php
- src/Phinx/Console/Command/Test.php
- src/Phinx/Migration/Manager.php
- tests/Phinx/Console/Command/BreakpointTest.php
- tests/Phinx/Console/Command/MigrateTest.php
- tests/Phinx/Console/Command/RollbackTest.php
- tests/Phinx/Console/Command/SeedRunTest.php
- tests/Phinx/Console/Command/StatusTest.php
- tests/Phinx/Migration/ManagerTest.php
Closes #1623
Currently, the exit codes were magic returned numbers within each command. This creates a class constant in AbstractCommand to use instead over all commands. I also moved the two status exit codes from the Manager to AbstractCommand as well to make the manager a bit more agnostic to how the console is working to make it potentially easier for someone to extend if they wanted to.
> Standardize exit codes to class constants

- src/Phinx/Console/Command/Migrate.php
- src/Phinx/Console/Command/Rollback.php
- tests/Phinx/Console/Command/MigrateTest.php
When running `rollback`, it prints out `ordering by [creation|execution] time` while migrate did not. This adds that print line to migrate to keep them consistent.
Added tests for when no order is provided (and defaults to creation) and when an order is provided.
> Print version order when running migrate

- src/Phinx/Db/Adapter/PostgresAdapter.php
- src/Phinx/Db/Table/Column.php
Main problem was I couldn't change the default SRID sent to geometry type columns.
Currently when using PostgresAdapter plus geometry type columns, all of them will have SRID 4326 and that can't be changed.
My PR adds a new option (srid) while adding columns so user can choose between leaving the default unchanged or not.
```php
$table->addColumn('column_name', 'geometry', ['srid' => 4674])->save();
```
P.S.: Didn't write PHP Unit tests because this would need PostGIS extension enabled on Postgres.
> Added the possibility to change the default SRID for geometry type

- phpunit.xml.dist
When specifying `localhost` as the host for MySQL, it will attempt to implicitly use a socket to connect, which fails when using docker-compose to host the DBs for testing purposes. Using 127.0.0.1 instead causes it to always use TCP which is fairly likely to always exist on default installations of mysql as well as works properly with the docker-compose setup.
> Fix default phpunit file to work with docker-compose

- src/Phinx/Db/Adapter/AdapterInterface.php
These three functions all accept a string or string[] types where if it receives a string, it casts it into a string[] anyway.
> Add string as allowed type in AdapterInterface functions

- docs/en/migrations.rst
Closes #1519
Adds a larger explanation of the differences between `save()` and `update()`/`create()` and why the latter is necessary/preferred for the `change()` method. I also fixed the one instance where `save()` was being called in a `change()` method in the docs.
I did leave the remaining instances of `save()` in the docs for the up/down usage, but can change those to explicit usage of `update()` and `create()` if so desired. However, the usages of them is fine and would not cause an error as-is if copied into the up/down method of someone else's migration. I guess the reason to change them to the explicit form would be if someone copied the statements into a change method.
> Add explanation of create/update vs save in docs

- src/Phinx/Db/Adapter/PdoAdapter.php
- tests/Phinx/Db/Adapter/PdoAdapterTest.php
Fixes #1685 (probably, I believe user there was using a `-` in table name, but have not yet confirmed).
If the `default_migration_table` in the configuration was set to something that required quoting, it would cause an error to be thrown, due to several places lacking quoting on the table name for the direct query. An example would be `phinx-log` would cause:
```
$ bin/phinx status
Phinx by CakePHP - https://phinx.org.
using config file ./phinx.yml
using config parser yaml
using migration paths
- /Users/mpeveler/Work/Github/phinx/db/migrations
using seed paths
warning no environment specified, defaulting to: sqlite
ordering by creation time
Status  [Migration ID]  Started              Finished             Migration Name
--------------------------------------------------------------------- …
```
> Fix schema table not being properly quoted in some queries

- UPGRADE_0.8.md
Closes #1000
Adds a note to the 0.8 upgrade guide for people that used phinx on a pre 5.7 MySQL with phinx and that were then looking to upgrade to 5.6.
> Add note about MySQL version incompatibility fix

- src/Phinx/Config/Config.php
- tests/Phinx/Config/ConfigTest.php
Depending on configuration of the php.ini setting `variables_order`, `$_ENV` is generally empty, but it is possible in some environments that this is not always true (an example would also be that all environment variables set by phpunit are available under `$_ENV`, and not `$_SERVER`), and so it is better to probably just iterate through both arrays to find any matching `PHINX_` replacement token, especially to retain backwards compatibility (if someone was setting stuff through htaccess or whatever).
Included test case to test that loading from both `$_SERVER` and `$_ENV` is supported, and that values from `$_SERVER` are preferred in conflicts.
May fix #1692, but I am not sure without additional information from the author.
> Use both $_SERVER and $_ENV for getting replacement config tokens

- composer.json
- src/Phinx/Config/Config.php
A bottom point from #1702 and my comment from https://github.com/cakephp/phinx/pull/1491#issuecomment-580784114.
Adds `ext-json` as a suggested package to be installed for phinx to function if using a JSON configuration file. I also add a check that the function exists before using it so that the error message can be a bit nicer (instead of throwing a fatal error with a stacktrace).
If this is merged #1491 should definitely be closed, given that its proposal was making ext-json mandatory (as it was when that PR was opened, but is no longer).
> Mark ext-json as optional and check it exists for usage

- src/Phinx/Wrapper/TextWrapper.php
With this simple PR we grant the TextWrapper status command the support for json output format
for ease of use.
> Improved Wrapper to support status command in json format

- Dockerfile
This PR updates the dockerfile to base based in PHP 7.2 rather than 7.1, fixing the issue with project dependencies. Closes #1708.
> Bump Dockerfile PHP version to 7.2

- src/Phinx/Db/Adapter/MysqlAdapter.php
- src/Phinx/Db/Adapter/PostgresAdapter.php
- src/Phinx/Db/Adapter/SqlServerAdapter.php
- tests/Phinx/Db/Adapter/MysqlAdapterTest.php
- tests/Phinx/Db/Adapter/PostgresAdapterTest.php
- tests/Phinx/Db/Adapter/SqlServerAdapterTest.php
At the moment if you define a `primary_key` but forget to set `'id' => false` then your intended `primary_key` is silently ignored and the standard auto increment `id` field is created instead.
This PR instead makes this configuration an error so that the user is aware they are doing something wrong and can decide whether to remove their `primary_key` to confirm the actual behaviour, or to add `'id' => false` to get their intended behaviour.
There was also a few instances of this mistake in the postgres tests, so this PR fixes those too
> Raise error on ignored primary key

- docs/en/migrations.rst
- src/Phinx/Db/Adapter/MysqlAdapter.php
- src/Phinx/Db/Adapter/SQLiteAdapter.php
- tests/Phinx/Db/Adapter/SQLiteAdapterTest.php
Fixes #1446
This brings the SQLite adapter inline with all other adapters, making it so that all creates columns as `NOT NULL` by default. SQLite does have an annoying "bug" where a column can be `NOT NULL` without specifying a default on table creation, but cannot if appending it to an existing table. I've added a note to the docs about this
Either this PR or #1687 should be merged and the other should be closed.
The change to the MySQLAdapter is just cosmetic to make it match the other adapters.
> Use not null by default for sqlite column definitions

- src/Phinx/Db/Adapter/MysqlAdapter.php
- src/Phinx/Db/Adapter/PostgresAdapter.php
- src/Phinx/Db/Adapter/SqlServerAdapter.php
- tests/Phinx/Db/Adapter/MysqlAdapterTest.php
- tests/Phinx/Db/Adapter/PostgresAdapterTest.php
- tests/Phinx/Db/Adapter/SqlServerAdapterTest.php
Fixes #1724
#1716 introduced an exception that is thrown if both `id` and `primary_key` are set. However, this includes the case where `primary_key` and `id` have the same value. This PR makes it so in the case that `id` and `primary_key` refer to the same value, no error is thrown.
So these are now valid again:
```
$this->table('table', ['id' => true, 'primary_key' => 'id'])->create();
$this->table('table', ['id' => true, 'primary_key' => ['id']])->create();
$this->table('table', ['id' => 'test', 'primary_key' => 'test'])->create();
```
> Allow explicitly setting primary key to same value as id

- src/Phinx/Db/Adapter/PdoAdapter.php
- tests/Phinx/Db/Adapter/PdoAdapterTest.php
If doing `phinx migrate --dry-run` without having previously run phinx, it would throw an exception as the `phinxlog` table is to be created as part of the dry run, but since it is not, this query then throws with the table not existing.
> Do not throw exception for missing phinxlog for dry run

- docs/en/migrations.rst
- src/Phinx/Db/Adapter/SQLiteAdapter.php
- tests/Phinx/Db/Adapter/SQLiteAdapterTest.php
SQLite has many limitations with the ALTER TABLE commands around dropping columns, altering them, etc. which have been covered in previous PRs. However, while SQLite does
support using ALTER TABLE to add columns, it comes with quite a bit of caveats which include not being able to define a NOT NULL without a default, cannot define a default that is a function (e.g. CURRENT_TIMESTAMP), etc. As such, to overcome these things which people probably would not expect coming from other DBs, this commit makes it so that add column commands, like the alter column and drop column commands, we create a temp table with our desired changes, then copy in all old data into.
Closes #1611 and removes the cop-out that was my original solution for #1718 (with something that works as expected).
> Improving handling of add column instructions in sqlite

- src/Phinx/Db/Adapter/AdapterInterface.php
- src/Phinx/Db/Adapter/MysqlAdapter.php
- src/Phinx/Db/Adapter/PostgresAdapter.php
- src/Phinx/Db/Adapter/SQLiteAdapter.php
- src/Phinx/Db/Table/Column.php
- tests/Phinx/Db/Adapter/MysqlAdapterTest.php
- tests/Phinx/Db/Adapter/PostgresAdapterTest.php
- tests/Phinx/Db/Adapter/SQLiteAdapterTest.php
First stab at https://github.com/cakephp/phinx/issues/1732
I might need some help, as I am not too familiar with the lower levels here.
> Start adding binaryuuid support.

- src/Phinx/Db/Adapter/MysqlAdapter.php
- tests/Phinx/Db/Adapter/MysqlAdapterTest.php
Closes #1677
MySQL 8 added support for setting the SRID attribute of a column. This makes it so that you could only insert geometries of that SRID into that column.
I've set-up a travis build with MySQL 8 to show the tests passing (though it shows a lot of failing other MySQL tests on 8): https://travis-ci.org/github/MasterOdin/phinx/builds/672758069
> Support setting SRID for geometry columns for MySQL 8+

- tests/Phinx/Config/ConfigTest.php
- tests/Phinx/Db/Adapter/DataDomainTest.php
- tests/Phinx/Db/Adapter/MysqlAdapterTest.php
#1320 had a number of deprecated phpunit test methods in it. This PR modifies them to use the not deprecated versions.
I also fixed a typo I introduced in #1730 from copying and pasting and not updating the string.
> Fix using deprecated phpunit methods

- .travis.yml
- box.json
Closes #1559 
As discussed in https://github.com/cakephp/phinx/issues/1559#issuecomment-610123985, this PR sets up Travis to generate a phar using [`humbug/box`](https://github.com/humbug/box)`. This will then be uploaded to a release as it's made through the [Travis Deploy](https://docs.travis-ci.com/user/deployment/releases/).
The `stub` and `main` key/value pairs were removed from the `box.json` file as they were the default values box was using anyway during the compile process and it recommends to. The `Herrera` packages were deprecated in favor of the `KevinGH` ones.
For this to work, someone with release access will have to use the [Travis-CI CLI](https://github.com/travis-ci/travis.rb) and do the following:
1. Remove the deploy section added in this PR
1. Run the following …
> Create and deploy phinx.phar on travis build for tags

- docs/config/all.py
I am not totally sure what all needs to change for publishing docs for a new version (should https://github.com/cakephp/phinx/wiki/Releasing-a-new-version-of-Phinx be updated?), but it looks like https://book.cakephp.org/phinx/0/en/intro.html lists 0.11 in the dropdown.
> Update docs config for 0.12

- composer.json
- src/Phinx/Config/Config.php
- src/Phinx/Config/ConfigInterface.php
- src/Phinx/Console/Command/AbstractCommand.php
- src/Phinx/Migration/Manager.php
- src/Phinx/Seed/AbstractSeed.php
For our use-case of Phinx, we require some complex services for generating the correct seed data. This creates difficulties in having to manually instantiate all the services within the init methods of the Seed. If users could provide a PSR-11 container that implements the psr/container package interface then it would allow for much more flexability in this regard, including auto-wiring.
> Support user-configured DI container instantiation of seeds

- .github/workflows/mysql8.yml
- tests/Phinx/Db/Adapter/MysqlAdapterTest.php
Closes #1751
MySQL 8.0.17 deprecated usage of the display width for integer data types, stating that it did not really do anything as it would allow integers to go beyond the specified width, and was only really used when you wanted to pad a number. The tests have been modified now to check on version of mysql to determine what the expected type for integer columns will be, but a more proper (and breaking) fix would be to probably not bother with display widths at all for MysqlAdapter.
> fix failing tests for mysql 8

- src/Phinx/Config/Config.php
- src/Phinx/Db/Adapter/SQLiteAdapter.php
- src/Phinx/Util/Util.php
- tests/Phinx/Config/ConfigDsnTest.php
- tests/Phinx/Config/ConfigTest.php
- tests/Phinx/Db/TableTest.php
This is preparation for replacing all the unit test defines with DB_DSN env variables similar to cakephp core.
The regex was replaced with the regex used by `StaticConfigTrait::parseDsn()` with two behavior changes:
- `name` does not include the leading `/`
- There is no `fragment` string parsed, only `query`
The only originally valid pattern that is now rejected is the random character string. The adapter names can't be completely arbitrary symbols now.
> Split parsing DSN out to utility helper

- composer.json
Re-creating #1762 to hopefully not have Travis-CI freak out like last time when I initially opened it against master and then tried to change the base post PR creation.
As discussed with @dereuromark, this re-adds `symfony/yaml` as a dependency to the 0.11.x branch, as this was a breaking change and should have been held off on for 0.12.x release.
Follow-up here after merging would be:
* cut new 0.11.x release
* Update release notes for 0.12.x to mention this breaking change (symfony/yaml no longer installed by default, if using yaml conf file, you must install this dependency yourself).
> add symfony/yaml back as dependency for 0.11.x

- src/Phinx/Db/Adapter/PostgresAdapter.php
- tests/Phinx/Db/Adapter/PostgresAdapterTest.php
Closes #1736
The binary type (bytesa) in postgres does not accept a limit option and will throw an error if attempting to use one (e.g. bytesa (32)). This fixes it so that the limit clause is properly ignored for it.
> Ignore limit option for binary type in postgres

- src/Phinx/Db/Adapter/PostgresAdapter.php
- tests/Phinx/Db/Adapter/PostgresAdapterTest.php
The code would use the value of numeric_precision to set a limit on integer columns. For integer values, this is set to the max range of the type (e.g. 2^32 for integer), but is not actually something the user can meaningfully use, nor has a counterpart for info coming into postgres in a migration, so better to just report null for limit instead.
> Do not set precision for integer columns coming from postgres DB

- src/Phinx/Console/Command/Create.php
- src/Phinx/Util/Util.php
- tests/Phinx/Console/Command/CreateTest.php
- tests/Phinx/TestUtils.php
- tests/Phinx/Util/UtilTest.php
Closes #566 (if it wasn't already closed for being "inactive"...)
Currently, the create command requires a name to be provided, and this is used for a suffix on the filename and then as the class name. This PR makes the name optional, such that if it is omitted, the system will automatically generate a name that is valid. The filename is "<datetime>_migration.php" and the class name is "V<Datetime>".
The filename is set-up such as the way it is since the classname must start with a string, and the `V` is for a future suggestion of potentially making phinx migration files be PSR-4 discoverable.
> Allow name to be optional for create command

- src/Phinx/Config/Config.php
- src/Phinx/Db/Adapter/SQLiteAdapter.php
- tests/Phinx/Config/ConfigTest.php
- tests/Phinx/Console/Command/MigrateTest.php
- tests/Phinx/Console/Command/RollbackTest.php
- tests/Phinx/Console/Command/SeedRunTest.php
Closes #1116.
Opened this more focused PR as #1773 was focused too heavily on the refactoring, and the discussion got me to think of a more elegant fix that bypasses the need for any of the refactoring anyway.
While the config test covers the fix well enough, leaving in the tests for the three affected commands as that is where people were hitting this bug, and also for just general validation of command output is good (as the tests are kind of severely lacking it overall).
The phinx docs specify that you can do the following:
adapter: sqlite
memory: true
and it will give you the in-memory DB of sqlite to use. However, before this commit, this would throw an error in migrate saying that "name" was not set, requiring you to add "name" with a bogus value to the above to get it work. This …
> Fix having to set name in config when using sqlite memory option

- .gitignore
Running sphinx build generated a number of files that are not currently caught by .gitignore.
> update gitignore rules for doc builds

- src/Phinx/Db/Adapter/PostgresAdapter.php
This ensures that getColumns will return results in column order and not potentially row order in the information_schema.columns table. While it's fairly impossible to get in this situation as the columns table is a view of an underlying system table, better to just follow best practices regardless in querying the table.
Due to the somewhat impossibility of actually getting columns to be out of order in the `getColumns` function to show a bug here (and without running the high risk of totally breaking postgres public schema), no test case is provided. However, as stated above, doing this is best practices, and does not leave phinx reliant on postgres implementation details that may or may not ever change. For reference, SQLServer already has the order by clause and MySQL and SQLite both …
> Use ordinal_position for postgres getColumns

- src/Phinx/Db/Adapter/SQLiteAdapter.php
- src/Phinx/Db/Adapter/SqlServerAdapter.php
phpstan 0.12.24 added the capacity to handle merging phpdocs, which was not the case for three functions which always threw, and so defined themselves as returning void. This removes the incompatible return, and adds a note to the functions that they always throw.
> Fix docstring return type for child methods that always throw

- src/Phinx/Db/Adapter/PdoAdapter.php
Simplifies the fetch functions in the PDOAdapter as they defined temporary variables they did not need, and `fetchAll` used a while loop to collect results instead of just using the native fetchAll function off the PDO class.
> simplify PdoAdapter fetch functions

- src/Phinx/Db/Adapter/MysqlAdapter.php
- tests/Phinx/Db/Adapter/MysqlAdapterTest.php
Fixes #887.
The previous implementation was relatively simplistic in that it would break if attempting to use a value with a `'` character in it and would give different result in getValues() after pulling the column out of the DB if it had a `'` or `,` in it. This patch makes the process more robust by using PDO::quote to handle values going in properly and then de-escapes things on the way out. Unfortunately, there's no builtin method we can use to get "unescaped" strings and have to do it by hand in custom fashion. Luckily, mysql's escape rules on values coming out of the DB are relatively simple with just really '' and \\ being the things we have to worry about.
> fix using quoted and escaped values for mysql enums

- tests/Phinx/Util/UtilTest.php
This adds unit tests specifically for parsing and not through a Config wrapper.
> Added unit tests for Util::parseDsn()

- docs/en/migrations.rst
- src/Phinx/Migration/Migration.template.php.dist
Closes #1747 
The docstring for the change function on migration is confusing as it implies that there's specific methods you can call to get reversible migrations, and that these methods are probably part of the MigrationInterface class. However, the referred to methods are actually part of the AdapterInterface, and are not reversible if called directly, but rather you must go through the Table API through its methods. This PR rewrites the docs to make that a bit clearer by using plain english for the actions that are reversible (with expectation that end user will translate into Table API calls).
To also simplify keeping things up-to-date on what can and cannot be reversed, and also making the docs a bit more of the authoritative source, the docstring in the Migration template is also …
> Improve docs on what can and cannot be reversed

- .github/workflows/mysql8.yml
#1782 broke the mysql8 github actions workflow as it converted the environment variable to an invalid yaml key/value, using a `=` instead of a `:` between the key and value in a dictionary.
Example of broken run: https://github.com/cakephp/phinx/actions/runs/107320570
> Fix gh-actions mysql8 workflow

- src/Phinx/Config/Config.php
Without adding something like [php-mock/php-mock](https://github.com/php-mock/php-mock), it's not possible to enter these if statements and so we should not collect code coverage statistics for it.
> Ignore un-testable function/class existence in Config

- docs/en/commands.rst
- docs/en/configuration.rst
The docs used `phinx.yml file` in a number of places where it would be better to use a more generic phrase like `phinx configuration file`, which better reflects that the config file could be in multiple different formats.
> replace phinx.yml with more generic words in docs

- .gitignore
- docs/en/commands.rst
- src/Phinx/Console/Command/AbstractCommand.php
- src/Phinx/Console/Command/Init.php
- tests/Phinx/Console/Command/InitTest.php
Wasn't sure if this should be on 0.13 or 0.12 as on the one hand it's a BC break, on the other hand, the current default (yml) does not work out of the box on 0.12 due to the making optional of symfony/yaml.
In 0.12, the symfony/yaml extension was made optional, which means it may no longer be available in a user's environment. As such, phinx should not default to using it for `init` as it may generate a file the user cannot actually use. Instead, we use `php` as the default as it's guaranteed to always work and be an available parser (as `ext_json` is equally optional).
Closes #1726
> use php as default configuration file format

- docs/en/migrations.rst
- src/Phinx/Db/Adapter/SQLiteAdapter.php
This also removes the attempt to use it in SQLite as that's incorrect and doing so will cause SQLite to error. Only MySQL uses the update clause now and this is clarified in the docs. Supporting it in other adapters will require the usage of triggers and such.
> specify that on_update is only usable on mysql

- src/Phinx/Db/Adapter/PostgresAdapter.php
Escape schema names so underscores and hyphens work. Also use 'CREATE SCHEMA IF NOT EXISTS'.
> Fix issues with Postgres schemas that contain hyphens and underscores.

- src/Phinx/Db/Adapter/MysqlAdapter.php
MySQL now only checks current database schema for Primary Key, rather than the entire server for a table name. #1799
> MySQL use schema name in getPrimaryKey

- src/Phinx/Db/Adapter/SqlServerAdapter.php
Simplifies the DSN construction for SQL Server by only putting the specific bit of DSN surrounded by a `if` clause, with the rest of it constructed outside of the `if` / `else` that was there. As a consequence, can drop the `else` and less duplication of strings.
> simplify constructing sqlserver dsn

- src/Phinx/Db/Table.php
- tests/Phinx/Db/TableTest.php
Link #868 . Updates don't reflect in the updated_at column for the default convenience methods.
> addTimestamps: update updated_at timestamp on row update

- docs/en/configuration.rst
As pointed out in #1813, there is no mention in the docs about setting the `default_migration_table` setting in the configuration. This adds such a subsection.
> add subsection on migration table to configuration doc

- src/Phinx/Migration/Migration.template.php.dist
- tests/Phinx/Console/Command/CreateTest.php
Since Phinx targets PHP >= 7.2, it is safe and probably a good idea to include the `strict_types` declaration. How good of an idea? Well, not *very* good, because Phinx's API appears to be entirely devoid of scalar type hints and also misses `array` type hints in [places where only arrays are valid](https://github.com/cakephp/phinx/blob/ac22eb22bd6bc36fab58610f385bc1f12d7f2150/src/Phinx/Db/Table.php#L295). However, once these areas are updated, templates from now on will be configured correctly to take advantage of type hints and the errors generated by mismatching types. Without these type hints, PHP just emits warnings such as `Invalid argument supplied for foreach() `, but continues regardless until something worse blows up later on.
You will also notice I added a few other bonuses …
> Changed migration template to adopt strict types

- src/Phinx/Db/Adapter/SqlServerAdapter.php
- tests/Phinx/Db/Adapter/SqlServerAdapterTest.php
Continuation of #1734
Closes #1746 
Adds `PHINX_TYPE_BINARYUUID` to SqlServer in a similar fashion to Postgres where it aliases to the same thing as `PHINX_TYPE_UUID` which is already a binary uuid field (`uniqueidentifier` in the case of SqlServer).
The tests here mimic the ones added for the other adapters from the above PR.
> Add support for BinaryUUID to SqlServer

- tests/Phinx/Db/Adapter/MysqlAdapterTest.php
This was missed when the test environment was updated.
> Replace hard-coded phinx db name with MYSQL_DB_CONFIG['name']

- src/Phinx/Db/Adapter/MysqlAdapter.php
- tests/Phinx/Db/Adapter/MysqlAdapterTest.php
This fixes the failing tests under MySQL 8.0.21+. As part of MySQL 8, the INFORMATION_SCHEMA tables were supposed to always return their columns as capitalized always (see . I guess pre 8.0.21, some tables would still return lowercase if the query was lowercase. This is related to changes done in #1759 along this same vein.
This should render #1836 unnecessary, and can leave phinx running against the latest version of mysql.
> Use capitalized references to INFORMATION_SCHEMA for mysql

- .travis.yml
With github actions setup, this reduces the configs run in travis similar to cakephp.
Adds php nightly build.
> Updated travis config to only run code coverage

- README.md
This adds a badge for GH actions to the README. The badge shows the status of the latest push to master (which is also where the link leads).
> Add GH action badge to README

- .travis.yml
- src/Phinx/Db/Adapter/PostgresAdapter.php
- tests/Phinx/Db/Adapter/PostgresAdapterTest.php
Closes #1832
Allows the `host` parameter for a postgres connection to be optional. If not defined, it will fallback to attempting to use a socket connection for PDO.
> allow host parameter for postgres to be optional

- .travis.yml
- tests/Phinx/Db/Adapter/PostgresAdapterTest.php
Fixes using the wrong variable from #1849 when passing the options to the new adapter instance.
Also updates the name of the environment variable per @othercorey's suggestion.
> fix postgres socket test to actually use socket options

- src/Phinx/Db/Adapter/PostgresAdapter.php
- tests/Phinx/Db/Adapter/PostgresAdapterTest.php
Closes #1851
The PostgresAdapter for rename column instructions does not quote the table name, causing it to use the default DB behavior which is to auto-cast everything to lowercase, which then fails to find the table to rename the column in. This patch makes it so that the table is properly quoted in the SQL instruction, and so that having it be mixed case works as expected.
Without the change, the test failed with this message:
```
1) Test\Phinx\Db\Adapter\PostgresAdapterTest::testMixedCaseColumns
PDOException: SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "organizationsettings" does not exist
/Users/mpeveler/Work/Github/phinx/src/Phinx/Db/Adapter/PdoAdapter.php:181
/Users/mpeveler/Work/Github/phinx/src/Phinx/Db/Util/AlterInstructions.php:123 …
```
> fix renaming columns in mixed case table in postgres

- .github/workflows/ci.yml
Updates the GH action workflow to run on all branches. As is, for in-progress work of mine, I cannot use GH actions to see if the test suite would pass or not, instead having to create a PR on my own repo to get the results. This greatly diminishes the valuableness of GH to me before I try opening a PR.
> update gh action to run on all branches

- tests/Phinx/Db/Adapter/MysqlAdapterTest.php
- tests/Phinx/Db/Adapter/PostgresAdapterTest.php
- tests/Phinx/Db/Adapter/SQLiteAdapterTest.php
- The PHPUnit accepts two approaches about calling assertions. And there're two approaches used on this repository.
- It seems that using the `$this` to call assertion times is greater than using `self::` to call assertions.
To be consistency, it should let all PHPUnit assertion methods call to be the `$this`.
> Consistency for assertion methods call

- src/Phinx/Db/Adapter/AbstractAdapter.php
- src/Phinx/Db/Adapter/MysqlAdapter.php
- src/Phinx/Db/Adapter/PostgresAdapter.php
- src/Phinx/Db/Adapter/SQLiteAdapter.php
- src/Phinx/Db/Adapter/SqlServerAdapter.php
- tests/Phinx/Db/Adapter/PostgresAdapterTest.php
This rewrites the `createdTables` cached to use the quoted table names, instead of just the table names as provided to the function. This fixes an issue where if a user on postgres created a table `table1` and then did `hasTable('public.table1')`, the cache would be missed as it would contain just `table1`, even though both things refer to the same thing. Interestingly, this showed an issue where the schema table (phinxlog) was being added somewhat inconsistently to the cache such that on dropping the database / schema, and then recreating it, the phinxlog table was entering the cache in slightly different ways, and so had to clear the cache on the reset of things (which makes sense anyway) or else the phinxlog table would complain about not existing when the system attempted to refer to …
> use quoteTableName when caching table name operations

- docker-compose.yml
Phinx is no longer compatible with postgres 9.2 (it throws an error on a simple migration, did not look deeply into why), and so the docker-compose image is no longer usable as is. Given that the CI tests the minimal version of 9.4, update the docker-compose file to match that.
> bump version of docker-compose postgres to currently supported version

- docker-compose.yml
- phpunit.xml.dist
The default phpunit DSN for mysql and postgres differed slightly from that used by docker-compose to set up these resources. Additionally, both differed from the DSN values used by the CI test suite under github actions. This unifies the values of phpunit and docker-compose to match each other, and that of the values used for CI.
> Update docker-compose/phpunit mysql and postgres to match DSN values

- tests/Phinx/Db/Adapter/MysqlAdapterTest.php
- tests/Phinx/Db/Adapter/PostgresAdapterTest.php
- tests/Phinx/Db/Adapter/SQLiteAdapterTest.php
- tests/Phinx/Db/TableTest.php
- Using the `assertTrue` to assert expected value is `true`.
- Using the `assertFalse` to assert expected value is `false`.
- Using the `assertNull` to assert expected value is `null`.
- Using the `assertCount` to assert expected count is same as result count.
> Improve assertions usage

- src/Phinx/Migration/Manager/Environment.php
This replaces the usage of the named function calls to a migration with the constants from MigrationInterface and calls to a seed with the constants from SeedInterface. This helps make the bind between them a bit more stable, in the rare case that the values of these constants were to change.
> Use Interface constants for function names

- tests/Phinx/Config/ConfigFileTest.php
- tests/Phinx/Config/ConfigReplaceTokensTest.php
- tests/Phinx/Console/Command/BreakpointTest.php
- tests/Phinx/Console/Command/CreateTest.php
- tests/Phinx/Console/Command/InitTest.php
- tests/Phinx/Console/Command/MigrateTest.php
- tests/Phinx/Console/Command/RollbackTest.php
- tests/Phinx/Console/Command/SeedCreateTest.php
- tests/Phinx/Console/Command/SeedRunTest.php
- tests/Phinx/Console/Command/StatusTest.php
- tests/Phinx/Db/Adapter/AdapterFactoryTest.php
- tests/Phinx/Db/Adapter/MysqlAdapterTest.php
- tests/Phinx/Db/Adapter/PdoAdapterTest.php
- tests/Phinx/Db/Adapter/PostgresAdapterTest.php
- tests/Phinx/Db/Adapter/ProxyAdapterTest.php
- tests/Phinx/Db/Adapter/SQLiteAdapterTest.php
- tests/Phinx/Db/Adapter/SqlServerAdapterTest.php
- tests/Phinx/Db/Adapter/TablePrefixAdapterTest.php
- tests/Phinx/Db/Table/ForeignKeyTest.php
- tests/Phinx/Migration/Manager/EnvironmentTest.php
- tests/Phinx/Migration/ManagerTest.php
- According to the [PHPUnit fixtures reference](https://phpunit.readthedocs.io/en/8.5/fixtures.html#more-setup-than-teardown), it should be `protected function setUp(): void` and `protected function tearDown(): void`.
> Improve PHPUnit fixtures

- src/Phinx/Db/Adapter/SQLiteAdapter.php
- tests/Phinx/Db/Adapter/SQLiteAdapterTest.php
Remake of #1847 with added testcase.
This fixes SQLite losing foreign keys when creating them in conjunction with indexes.
Closes #1840
Closes #1841
There's a good chance this will also close #988 and #1489 which the above issues seem to be duplicates of.
> Fixes problems in SQLite Adapter in foreign key creation

- tests/Phinx/Db/Adapter/SQLiteAdapterTest.php
Something I noticed while working on other stuff. Updates the test function to use `expectException` and `expectExceptionMessage`, which is the recommended way of testing this kind of thing, instead of the older try/catch methodology.
> Update test to use expectException phpunit method

- src/Phinx/Db/Adapter/SQLiteAdapter.php
- tests/Phinx/Db/Adapter/SQLiteAdapterTest.php
Closes #1857 
Adds support in `hasForeignKey` for named constraints in sqlite. Like the other providers, if you pass in both columns and constraint name, it will only look at the constraint name, and ignore the columns argument. Sqlite still does not have the capacity to drop foreign keys via name, which will come in a follow-up PR.
> support looking up foreign key by name in sqlite3

- composer.json
Support for PHP 8 was added in the 9.x line. However, cannot upgrade to it singularly as 9.x also dropped support for PHP 7.2, which phinx still supports. As such, we allow the installation of either ^8.5 or ^9.3, to be resolved by composer on the system in question, which works for development as phinx repository does not provide a composer.lock file.
> widen compatible phpunit range

- src/Phinx/Db/Adapter/AbstractAdapter.php
- src/Phinx/Db/Adapter/AdapterInterface.php
- src/Phinx/Db/Adapter/AdapterWrapper.php
- src/Phinx/Db/Adapter/PdoAdapter.php
Removes the deprecated function hasSchemaTable. This has been deprecated for 6+ years, and is probably safe to remove in terms of giving advance notice.
> remove deprecated hasSchemaTable function

- src/Phinx/Migration/AbstractMigration.php
- src/Phinx/Migration/MigrationInterface.php
- tests/Phinx/Migration/AbstractMigrationTest.php
This method was deprecated 2+ years ago. Given no one has complained about it, safe to remove I think, and make the recommended way the only way to do it.
> remove insert method from MigrationInterface

- src/Phinx/Db/Table/Column.php
Closes #1876 
This removes the exception thrown for setting a collation or encoding for an invalid column type, instead pushing it down to an expectation on the DB throwing an exception for us. It's probably preferable to do this as then phinx is not responsible for maintaining a list of valid types (some which may be only valid for specific adapters if collation is expanded to other DBs like postgres) and also avoiding a potential quagmire with dealing with someone using collation with a valid `Phinx\Util\Literal` (e.g. `Phinx\Util\Literal::from('longtext')`) or god forbid if they're allowed with custom types.
There was no prior test on the exception case for these functions, and there are existing types on the usage of collation / encoding, so no tests were introduced, changed, or …
> remove check on column type for setting collation / encoding

- src/Phinx/Db/Adapter/AdapterInterface.php
- src/Phinx/Migration/MigrationInterface.php
- src/Phinx/Seed/SeedInterface.php
This is a continuation of work done in #1691, where it only updated the return type of the `MigrationInterface`, and not the `SeedInterface`.
The underlying driver by default will always return a `PDOStatement`, and never an array, so the typehint here causes issues downstream in typing help. Changed it to mixed as the above PR notes, a custom adapter may implement any return type, and so cannot make it more specific than that here.
I also updated the docstrings of two other query methods to indicate that they do not infact return arrays, and their return type is based on the underlying adapter implementation.
> mark return type of SeedInterface::query as mixed

- src/Phinx/Db/Adapter/AbstractAdapter.php
- src/Phinx/Db/Adapter/MysqlAdapter.php
- src/Phinx/Db/Adapter/PdoAdapter.php
- src/Phinx/Db/Adapter/PostgresAdapter.php
- src/Phinx/Db/Adapter/SQLiteAdapter.php
- src/Phinx/Db/Adapter/SqlServerAdapter.php
- src/Phinx/Db/Table.php
- src/Phinx/Db/Table/Column.php
- tests/Phinx/Db/Adapter/MysqlAdapterTest.php
- tests/Phinx/Db/Adapter/PostgresAdapterTest.php
- tests/Phinx/Db/Adapter/SQLiteAdapterTest.php
- tests/Phinx/Db/Adapter/SqlServerAdapterTest.php
- tests/Phinx/Db/Table/ColumnTest.php
Closes #1817 
This makes it so that newly added columns are `NULL` by default, instead of `NOT NULL` except in the case of a column that uses the `identity` option, and does not also set a `null` option.
This is definitely BC breaking, and the release notes should make a big note that all previously written migrations will have to be updated to take into account the new null default, unless the authors were already explicit about the null status within their migrations.
> Set column null by default unless identity

- src/Phinx/Migration/AbstractMigration.php
- src/Phinx/Migration/MigrationInterface.php
- tests/Phinx/Migration/AbstractMigrationTest.php
Closes #1870 
Given that there's no docs right now for `createDatabase` either, did not elect to add them here (as not sure where to place them). For now, it should at least make it a bit easier for user discovery.
PR made against 0.13 due to breaking change on the MigrationInterface
> add createSchema and dropSchema methods on MigrationInterface

- src/Phinx/Migration/Manager.php
- src/Phinx/Migration/Manager/Environment.php
Closes #1818
This makes it so that the `preFlightCheck` and `postFlightCheck` are now run immediately before and immediately after the migration is run. This gives the advantage that one could run stuff against the adapter if they wanted to in the preFlightCheck, and that the `postFlightCheck` will run before the migration is logged as having run. This is especially beneficial in the latter's case given that by default, it will throw an exception if the user has incomplete table operations.
While this does slightly change the order things and run in, and that the checks are run within the migration timer, it's not really BC breaking enough to warrant necessarily going in the 0.13.x line only.
> run preFlightCheck and postFlightCheck immediately after migration

- src/Phinx/Db/Adapter/PdoAdapter.php
- tests/Phinx/Db/Adapter/MysqlAdapterTest.php
Allow for the following:
```
$this->table('exampleFailure', [
'id' => false,
])
->addColumn('created_at', 'timestamp', [
'null' => false,
'default' => 'CURRENT_TIMESTAMP(3)',
'limit' => 3,
'after' => 'displayType',
])
->create();
```
which before gave the following "Syntax error or access violation: 1067 Invalid default value for 'created_at'" as it was a quoted string of
> Mysql - Ensure a default of CURRENT_TIMESTAMP(3) is not quoted

- src/Phinx/Migration/AbstractMigration.php
- src/Phinx/Migration/Manager/Environment.php
- src/Phinx/Migration/MigrationInterface.php
The argument to the flight checks is unnecessary now with the change from #1873 as now `preFlightCheck` will be run after the `setMigratingUp` method has been called (previously it was not). This was change was not done in #1873 to allow that patch to land in 0.12.x release, while the clean-up here will coincide with other BC breaking changes to the interfaces.
> remove extraneous argument to flightChecks

- .stickler.yml
As suggested on slack, this makes it so that stickler-ci should use the same standard as phpcs. This allows developers to test their code locally and expect it to then pass the stickler on PR creation reasonably (e.g. like in #1888), and vice versa.
The next step would be to look at `cakephp/cakephp-codesniffer:^4` for phpcs, but that will require a much greater scope of change which I think should be done peacemeal over time.
> Use CakePHP 3 code standard for stickler

- src/Phinx/Config/Config.php
- tests/Phinx/Config/ConfigTest.php
- tests/Phinx/Console/Command/MigrateTest.php
- tests/Phinx/Console/Command/SeedRunTest.php
- tests/Phinx/Console/Command/StatusTest.php
This was deprecated with the 0.12 release, but was only deprecated within the release notes. This adds a deprecation notice into the codebase that is triggered on usage to hopefully help ensure users are not surprised when this does actually get removed.
> trigger deprecation notice when using default_database

- docs/en/configuration.rst
- docs/en/migrations.rst
- docs/fr/configuration.rst
- docs/fr/migrations.rst
- docs/ja/configuration.rst
- docs/ja/migrations.rst
- src/Phinx/Db/Adapter/MysqlAdapter.php
- tests/Phinx/Db/Adapter/MysqlAdapterTest.php
- tests/Phinx/Migration/_files/drop_column_fk_index_regression/20190928205056_first_fk_index_migration.php
- tests/Phinx/Migration/_files/drop_column_fk_index_regression/20190928205060_second_fk_index_migration.php
closes #1763
This makes `utf8mb4_general_ci` the default collation for MySQL tables over `utf8_general_ci`. The prior default made sense 7+ years ago when computing power for servers was more limited, but nowadays, the performance gained is increasingly minimal over the necessary deal of handling the greater nuances of capitalization of different languages and their characters by default that the original `utf8` schema lacked for MySQL.
> make utf8mb4_unicode_ci default collation for new mysql tables

- tests/Phinx/Db/Adapter/MysqlAdapterTest.php
This was left in by accident when the dependency was removed.
> Remove unused import from MysqlAdapter

- docs/en/migrations.rst
Looking at the docs for another thing, I realized I forgot to update them in the PR that changed the default behavior of the null option. I could not figure out what the `see below` bit was referring to, so removed that.
> update docs on default value of null option

- tests/Phinx/Console/Command/BreakpointTest.php
- tests/Phinx/Console/Command/MigrateTest.php
- tests/Phinx/Console/Command/RollbackTest.php
- tests/Phinx/Console/Command/SeedRunTest.php
- tests/Phinx/Console/Command/StatusTest.php
- tests/Phinx/Console/PhinxApplicationTest.php
- tests/Phinx/Db/Adapter/MysqlAdapterTest.php
- tests/Phinx/Db/Adapter/PostgresAdapterTest.php
- tests/Phinx/Db/Adapter/SQLiteAdapterTest.php
- tests/Phinx/Db/Adapter/SqlServerAdapterTest.php
- tests/Phinx/Db/TableTest.php
- tests/Phinx/Migration/ManagerTest.php
`assertRegExp` was deprecated in PHPUnit 9 (and to be removed in PHPUnit 10) and instead you are supposed to use `assertMatchesRegularExpression`. While we cannot remove all usages of `assertRegExp` as phinx still requires PHPUnit 8 when testing against PHP 7.2, there were a number of places where `assertRegExp` could be replaced with `assertStringContainsString` and accomplish the same test result, while also getting rid of a bunch of warnings about how that function was deprecated.
> replace assertRegExp with assertStringContains where possible

- src/Phinx/Db/Adapter/MysqlAdapter.php
- tests/Phinx/Db/Adapter/MysqlAdapterTest.php
This makes `biginteger` work as the other integer types for mysql where it has a default, but you can override it.
Opening this PR here just so I don't forget about this as I noticed this while working on a project that used phinx. Will add a test shortly.
> Allow setting limit option for big int for mysql

- docs/en/migrations.rst
- src/Phinx/Db/Adapter/MysqlAdapter.php
- tests/Phinx/Db/Adapter/MysqlAdapterTest.php
Closes #655. (Only 5 years later.)
This is a MySQL-only syntax (as is the `AFTER` syntax to begin with) so no other adapters are relevant.
Since the Phinx repo isn't labeled with `hacktoberfest`, could I kindly request adding the `hacktoberfest-accepted` to this PR upon approval please?
> Add MySQL FIRST support.

- docs/en/configuration.rst
- src/Phinx/Db/Adapter/MysqlAdapter.php
- src/Phinx/Db/Adapter/PdoAdapter.php
- src/Phinx/Db/Adapter/SqlServerAdapter.php
- tests/Phinx/Db/Adapter/MysqlAdapterTest.php
- tests/Phinx/Db/Adapter/PdoAdapterTest.php
- tests/Phinx/Db/Adapter/PostgresAdapterTest.php
- tests/Phinx/Db/Adapter/SQLiteAdapterTest.php
- tests/Phinx/Db/Adapter/SqlServerAdapterTest.php
Closes #1844
This allows specifying a list of PDO options that are then set against the connection using the `setAttribute` method. This follows a similar design of the adapter specific options of checking against a specific prefix. This is BC breaking in that it reserves `attr_` for options, but there is no option with that value so it should not affect anyone's code unless they were adding extraneous things to their config.
I've also added documentation on setting these options, both the generic ones and the adapter specific ones with a simple example, as I could not find a mention of it before in the docs.
> add ability to set generic PDO attributes

- docs/en/migrations.rst
Closes #1802
Consolidates the "Valid Column Types" section to just be under the "Working with Columns" section, and also moves the usage of the `Literal::from` there as well as it's also couched in usage within columns and the like.
> conslidate column types and values to single place

- docs/en/migrations.rst
- src/Phinx/Db/Adapter/MysqlAdapter.php
- tests/Phinx/Db/Adapter/MysqlAdapterTest.php
- tests/Phinx/Migration/_files/drop_column_fk_index_regression/20190928205056_first_fk_index_migration.php
- tests/Phinx/Migration/_files/drop_index_regression/20121213232502_create_drop_fk_initial_schema.php
- tests/Phinx/Migration/_files/drop_table_with_fk_regression/20190928205060_second_drop_fk_migration.php
- tests/Phinx/Migration/_files/reversiblemigrations/20121224200852_create_user_logins_table.php
- tests/Phinx/Migration/_files/reversiblemigrations/20190928220334_add_column_index_fk.php
- tests/Phinx/Migration/_files_baz/reversiblemigrations/20151224200852_create_user_logins_table.php
- tests/Phinx/Migration/_files_foo_bar/reversiblemigrations/20161224200852_create_user_logins_table.php
closes #1780
This changes it so that the default PK for a table (either by not specifying one at all, or just setting the `id` option for the table) is unsigned by default, instead of signed. This gives users extra space to store IDs in their databases, and is generally considered the "right" definition to have for an auto incrementing column for mysql, with some amount of other ORM / DB stuff out there doing this as well.
The principle downside is that foreign key columns will have to be specified with `"signed" => false` now, but I think is balanced out by the upsides of doing this.
> make default PKs for mysql unsigned by default

- docs/en/migrations.rst
- src/Phinx/Db/Adapter/PostgresAdapter.php
- tests/Phinx/Db/Adapter/PostgresAdapterTest.php
Debated on whether to make this against master or 0.next, and decided for 0.next as this is a breaking chang, albeit a small one.
Closes (properly) #1693
Using the column type `smallinteger` with `identity = true` will produce `SMALLSERIAL` data type. This mirrors the usage of `biginteger` producing `BIGSERIAL`.
> add support for smallserial alias for postgres

- README.md
#1928 replaced coveralls with codecov, but did not update the badge in the README for the service.
> Replace coveralls badge with codecov

- .github/workflows/ci.yml
Given the consolidation onto GH actions for the full test suite, see no reason to not also run codecov for windows/sqlserver now, in addition to the other DB adapters. This should improve the experience for submitting sqlserver patches as well as now codecov will not be an instant failure on adding lines because sqlserver has never been considered on the coverage count.
On completion with these changes, codecov reports:
> 88.39% (+8.58%) compared to 30faad2
> Run codecov for sqlserver test suite

- src/Phinx/Config/Config.php
Both have the same conceptual idea and work the same in this instance, but probably better to use the function built for the purpose of answering "does this environment exist" than the "get this environment" function.
> Replace getEnvironment existence check with hasEnvironment

- src/Phinx/Config/Config.php
My IDE complained about how this statement was deprecated in PHP 7.4, and adding the parentheses fixed that, while also making the whole thing a bit more readable and less likely to have weird right/left parse differences.
> add parentheses to nested ternary statement

- src/Phinx/Db/Adapter/SQLiteAdapter.php
> 1) Migrations\Test\TestCase\MigrationsTest::testMigrateErrors
Failed asserting that exception of type "Error" matches expected exception "Exception". Message was: "Call to a member function getName() on bool" at
/.../vendor/robmorgan/phinx/src/Phinx/Db/Adapter/SQLiteAdapter.php:696
> Avoid error

- tests/Phinx/Db/Adapter/SQLiteAdapterTest.php
This adds a test case for the change made in #1927 so that I do not potentially re-introduce the regression that it fixed which I caused in #1845. I did not add the error message here as it's somewhat irrelevant and to make the test less brittle as the important thing is the data provider is throwing the error here, not the code itself.
For reference, the error message thrown is a SQL error on invalid `)` which happens as we hit query `INSERT INTO temp_non_existing_table () SELECT * FROM non_existing_table` (or something of that nature).
> Add test case for sqlite for new table adding column using update

- .github/workflows/phar.yml
Migrates the generation of the phar archive from Travis to a GH action, as noted in #1928. When the time comes to cut a new release, this action should be validated that it actually ran / worked, as it looks like the phar archive generation has been broken for recent releases.
> add GH workflow for generating phar file for releases

- src/Phinx/Db/Adapter/AdapterInterface.php
- src/Phinx/Migration/MigrationInterface.php
- src/Phinx/Seed/SeedInterface.php
The PHPDoc for FetchRow omits [false as a possible return](https://www.php.net/manual/en/pdostatement.fetch.php), which impedes proper error handling when using the method, or can all-but prevent error handling if using in conjunction with static analysis tools which emit logic exceptions on statements that contradict the declared return types in PHPDoc.
This PR resolves that by making the return of fetch row falseable. 
This will have the unfortunate consequence of highlighting in static analysis tools any areas where false is ignored as a possible return type, which could cause issues in existing usages.
> Add false to PHPDoc for FetchRow return

- src/Phinx/Db/Adapter/PostgresAdapter.php
- tests/Phinx/Db/Adapter/PostgresAdapterTest.php
Since bigint has the largest range of numbers I used it to convert a value to a number and no need to worry about smaller numbers. I also added 3 different tests for different types of integers. I'm not sure if this is the right thing to do now, but there may be some changes with the types in the future.
> Fix :: Postgres :: Change column type from text to integer | fixed #1940

- src/Phinx/Db/Table.php
Doc blocks for `Table::addForeighKey()` and `Table::addForeignKeyWithName()` both referenced `\Phinx\Db\Table` for the parameter `$referencedTable`. In practice this parameter was simply passed to `AddForeignKey::build()` which takes a `\Phinx\Db\Table\Table`. 
Updated the doc block to the correct type. I did not add an automated conversion from `\Phinx\Db\Table` to `\Phinx\Db\Table\Table` as that would break existing code calling the methods.
> Fixed type hint in doc-block.

- docs/en/commands.rst
- src/Phinx/Console/Command/SeedCreate.php
- tests/Phinx/Console/Command/SeedCreateTest.php
- tests/Phinx/Console/Command/Templates/SimpleSeeder.template.php.dist
Adds the -t option to seed:create command, just like it exists for create command.
I've updated English documentation.
> Added alternative template option to seed create command

- .github/workflows/ci.yml
This simplifies the GH workflow trigger events, as well as should fix an issue where branches that have a `/` will not be triggered for the push event.
> Simplify gh workflow event triggers

- src/Phinx/Migration/AbstractMigration.php
- tests/Phinx/Migration/AbstractMigrationTest.php
Function has been deprecated since 0.10.0. Probably safe to remove I think.
> Remove deprecated dropTable function

- docs/en/configuration.rst
- src/Phinx/Console/Command/AbstractCommand.php
- src/Phinx/Util/Util.php
Currently, it is not possible to use the `$output` or `$input` of the command when running the bootstrap script. Which requires you to just `echo` any progress/diagnostic output or create your own output handler but then you would also have to parse the original verbosity parameters and so forth.
Passing the `$input` and `$output` parameters from the [`bootstrap()`-method](https://github.com/cakephp/phinx/blob/9457e3879b0abc02a4022941a6a535141889432e/src/Phinx/Console/Command/AbstractCommand.php#L105) will make them available in the included script as `$input` and `$output` respectively.
That would be enough for just output handling. But it would also be great to be able to access the command object itself, so there is also access to the config (via `getConfig()` and all the other …
> Provide $input, $output, and $context variable to bootstrap script

- docs/en/configuration.rst
- src/Phinx/Config/Config.php
- src/Phinx/Db/Adapter/AbstractAdapter.php
- tests/Phinx/Config/ConfigTest.php
- tests/Phinx/Db/Adapter/PdoAdapterTest.php
Closes #1896 
This sets it so that it is now possible to set the migration table per environment, falling back to the `default_migration_table` if one is not set for that environment. I think this is probably a more elegant solution to things. As part of this change, the `AbstractAdapter` now expects the `migration_table` to be used as an option instead of `default_migration_table`, though both are allowed, with the latter throwing a deprecation warning.
> Allow setting migration_table per environment

- src/Phinx/Db/Adapter/SQLiteAdapter.php
- tests/Phinx/Db/Adapter/SQLiteAdapterTest.php
This results in the error: `1 index associated with UNIQUE or PRIMARY KEY constraint cannot be dropped`
> Fix error when creating a foreign key on a table without an autoincrementing primary key in SQlite

- docs/en/configuration.rst
Adds note about MySQL transactions not working for DB migrations in the adapter section of the docs per discussion in #1964.
> add MySQL limitation section to docs

- src/Phinx/Db/Adapter/PostgresAdapter.php
- tests/Phinx/Db/Adapter/PostgresAdapterTest.php
For boolean start by dropping defaults since its value is not a bool,
then convert all non-zero values to boolean true.
For uuid add USING:uuid
> Postgres allow change from int to bool and char to uuid

- src/Phinx/Db/Table.php
This adds a new method to the `Table` object to allow checking for the existence of a primary key. This mirrors the existing `hasForeignKey` function on the object.
> Expose hasPrimaryKey method in Table object

- docs/en/migrations.rst
- docs/en/seeding.rst
- src/Phinx/Migration/AbstractMigration.php
- src/Phinx/Migration/Manager.php
- src/Phinx/Migration/MigrationInterface.php
- src/Phinx/Seed/AbstractSeed.php
- src/Phinx/Seed/SeedInterface.php
- tests/Phinx/Migration/ManagerTest.php
- tests/Phinx/Migration/_files/seeds/UserSeederNotExecuted.php
- tests/Phinx/Migration/_files/should_execute/20201207205056_should_not_execute_migration.php
- tests/Phinx/Migration/_files/should_execute/20201207205057_should_execute_migration.php
The company I work for uses Phinx and we are pleased with it. However what's currently stopping us from using it in production is not being able to run migrations in two steps, before and after deployment.
This is an issue that's been raised several times already, in #529, #1044, #1619 and #1824 
I started using my own implementation of AbstractMigration and creating a custom template, but I realized that there was a key feature that I was missing if I did not want to wrap all my code in big `if` conditions in all my migrations: a way to stop the migrations from being executed at the Manager level, before it inserts data in phinxlog. This was rightly suggested here: https://github.com/cakephp/phinx/issues/1619#issuecomment-578732670
Even with `if` conditions as mentioned in #1619, the …
> Add new shouldExecute method to prevent a migration or seeder from being executed

- src/Phinx/Db/Adapter/AdapterInterface.php
- src/Phinx/Db/Adapter/SqlServerAdapter.php
Differentiate between geometry and geography columns in sql server
> Add geometry column to sql server adapter

- .github/workflows/ci.yml
The mysql tests have started failing with decent frequency. This seems to be a timing error where we hit the step to create the DB before the mysql container is ready, causing the suite to fail. This surfaces as the error "ERROR 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet', system error: 0" in the logs.
This PR adds some basic retry logic around the command so that it will run the DB creation command 5 times over 10 seconds (with a 2 second pause between tries). This followed by a simple `SELECT 1` query to ensure the DB is up. This helps deal with the flakiness here, getting the test suite to pass consistently again. This job (https://github.com/MasterOdin/phinx/runs/2793008084?check_suite_focus=true) shows the effect where under `Setup …
> Add retry logic around mysql db creation

- docs/en/migrations.rst
- src/Phinx/Db/Table.php
- tests/Phinx/Db/TableTest.php
Closes #1985 
This allows using the boolean `false` for the first two arguments to `addTimestamps` and `addTimestampsWithTimezone` to have it skip adding that column to the table.
> allow setting column to false to ignore it in addTimestamps

- src/Phinx/Db/Adapter/SQLiteAdapter.php
- tests/Phinx/Db/Adapter/SQLiteAdapterTest.php
Allow subclasses to override the fields
Example use case: Map ENUM to VARCHAR
> Access static fields statically

- src/Phinx/Db/Adapter/AdapterInterface.php
- src/Phinx/Db/Adapter/MysqlAdapter.php
- src/Phinx/Db/Table/Column.php
- tests/Phinx/Db/Adapter/MysqlAdapterTest.php
This Pull requests solves issue #1996. Correctly adding the mediumint type to mysql. Together on this patch, one of the PHPUnit tests was changed to ignore case, due to differences between MySQL and MariaDB
> Adding the mediumint type for the MySql adapter

- src/Phinx/Db/Adapter/MysqlAdapter.php
This PR adds table schema on the SQL JOIN clause when retrieving a table's primary key.
Fixes issue #2000.
> Fixes issue with MySQL Adapter primary key getter

- phpstan-baseline.neon
- phpstan.neon
There's an open bug in phpstan that's triggering an error on usage of `is_subclass_of` (see https://github.com/phpstan/phpstan/issues/5369). While we wait for a fix, this PR adds a baseline file to ignore the reported error, so that the build will no longer fail.
> Add baseline for phpstan to workaround analysis bug

- src/Phinx/Db/Adapter/SQLiteAdapter.php
- tests/Phinx/Db/Adapter/SQLiteAdapterTest.php
This PR fixes adding columns to a table created outside of phinx and its create table syntax. When creating a table in SQLite, it saves the create sql statement directly and returns that exact copy when querying `sqlite_master` for the script. Phinx was setup to only expect the create statement that it would generate, while there's a number of ways to write that statement, with various places to put newlines, extra spaces, different quotation styles, etc. This PR adds a new normalization step when we fetch the create table syntax to make working with it consistent regardless of how the table was originally created.
Closes #2035
> Fix adding column to sqlite table created outside phinx

- docs/en/migrations.rst
Line 309: $this->table('status')->insert($rows)->save() should probably just be $table('status')->insert($rows)->save() without referencing $this.
> Change incorrect reference to $this

- docs/en/migrations.rst
#2041 changed the insert docs example to have invalid code. This fixes the example to what the intended change was (just referencing the variable `$table` instead of class method `$this->table`. I also reordered some of the other bits of code so that the example is a bit more symmetric in general between one row insertion and multiple row insertion.
> Clean up insert data doc example

- src/Phinx/Db/Table.php
Replace `specific` with `specify`, and alter the sentence slightly to indicate that both options can be set simultaneously.
> Fix docs spell error

- src/Phinx/Console/Command/AbstractCommand.php
- src/Phinx/Console/Command/Breakpoint.php
- src/Phinx/Console/Command/Create.php
- src/Phinx/Console/Command/ListAliases.php
- src/Phinx/Console/Command/Migrate.php
- src/Phinx/Console/Command/Rollback.php
- src/Phinx/Console/Command/SeedCreate.php
- src/Phinx/Console/Command/SeedRun.php
- src/Phinx/Console/Command/Status.php
- src/Phinx/Console/Command/Test.php
- src/Phinx/Console/PhinxApplication.php
- src/Phinx/Migration/Manager.php
- tests/Phinx/Console/Output/RawBufferedOutput.php
Sort of fixes #1568
If use `--no-info` there would be no additional information. Especially useful for creating migration files with all migrations in one.
Output before:
```
Phinx by CakePHP - https://phinx.org.
using config file phinx.php
using config parser php
using migration paths 
- /var/www/db/migrations
using seed paths 
- /var/www/db/seeds
warning no environment specified, defaulting to: docker
using database ncc
ordering by creation time
== 20211213143400 TestMig: migrating
START TRANSACTION;
CREATE TABLE `test_a` (`id` INT(11) NOT NULL AUTO_INCREMENT, `name` VARCHAR(255) NOT NULL, `value` VARCHAR(255) NOT NULL, `comment` VARCHAR(255) NOT NULL, PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET utf8 COLLATE utf8_general_ci;
COMMIT;
INSERT INTO `phinx_migration_log` (`version`, …
```
> Do not print information output with option --no-info

- src/Phinx/Console/Command/Create.php
- tests/Phinx/Console/Command/CreateTest.php
This PR will slightly improve the test coverage for the `Create` command.
You may also ask why I removed 2 sections related to path checking.
The reason behind that is the fact, that `getMigrationPaths()` already checks if the given (or default) path is present and valid.
If not it already throws an exception [here](https://github.com/cakephp/phinx/blob/master/src/Phinx/Console/Command/Create.php#L105) and therefore can never get to those other 2 checks.
> improve tests for create command

- src/Phinx/Wrapper/TextWrapper.php
- tests/Phinx/Wrapper/TextWrapperTest.php
Currently, within the `TextWrapper::class`, in the methods `TextWrapper::getStatus()`, `TextWrapper::getMigrate()`, `TextWrapper::getSeed()`, `TextWrapper::getRollback()` the following expression: `if ($env ?: $this->hasOption('environment'))` is used.
If I am correct, that would mean that the inner short hand ternary would first have to evaluate before the outer if would evaluate its result. Hence there would be two evaluations of the value's truthiness. This pull request removes the use of the shorthand ternary and replaces it by a logical or.
The added tests should confirm that equivalent behavior is maintained (although tests are written for one method implementation).
In case there has been anything I overlooked please inform me, or if you have any additional requests please let me …
> TEXT WRAPPER: Refactor shorthand ternary & add tests

- docs/en/migrations.rst
There is a `->save();` missing in the renameColumn block.
> Add missing save call to renameColumn doc examples

- src/Phinx/Db/Adapter/SqlServerAdapter.php
- tests/Phinx/Db/Adapter/SqlServerAdapterTest.php
Fixes #2093
This PR adds _TrustServerCertificate=true_ to the connection string. This is needed for sqlserver 2017 and 2019. Tested that phinx works with sqlsrv 2019 after this fix.
@markstory
> Add TrustServerCertificate to SqlServerAdapter

- src/Phinx/Db/Adapter/SqlServerAdapter.php
- tests/Phinx/Db/Adapter/SqlServerAdapterTest.php
The `SqlServerAdapter::parseDefault($default)` function returns `""` if `$default` is `null`
Because of the returned empty string, the column can not be **changed** to have an empty string as default value (no differnce detected)
Example for an existing column which has no effect:
```php
$this->table('tableName')->changeColumn('columnName', 'string', ['default' => '', 'null' => false])
```
> Fix SqlServerAdapter returning empty string instead of null for column default

- src/Phinx/Db/Adapter/SQLiteAdapter.php
- tests/Phinx/Db/Adapter/SQLiteAdapterTest.php
PR fixes a bug where altering sqlite tables that had indexes or triggers would drop the indexes or triggers. This was because indexes and triggers are not contained in the `CREATE TABLE` sql that we used to create a table copy the indexes and triggers would be get copied over, and so on dropping the original table it would delete the indexes and triggers, and the rename would not bring them back.
This PR adds new post steps of recreating the indexes and triggers after we rename the temporary table we created back to its original name.
Fixes #1290
> Maintain indexes / triggers after altering sqlite tables
