src/Phinx/Config/Config.php, src/Phinx/Console/Command/AbstractCommand.php, src/Phinx/Console/Command/Create.php, src/Phinx/Migration/Migration.template.php.dist, tests/Phinx/Config/ConfigTest.php
Allow migration base class to be any namespace\class.
=> Support any namespace\class for the migration base class.

docs/migrations.rst
(otherwise one would need to dig through the code to find where MysqlAdapter is defined)
=> Docs: import the namespace where MysqlAdapter is

src/Phinx/Db/Adapter/AdapterInterface.php, src/Phinx/Db/Adapter/MysqlAdapter.php, src/Phinx/Db/Table/Column.php, tests/Phinx/Db/Adapter/MysqlAdapterTest.php, tests/Phinx/Db/Adapter/MysqlAdapterUnitTest.php
Added as saparate PR - based on #452
=> Added ENUM and SET types for MySQL

src/Phinx/Db/Adapter/PostgresAdapter.php
[#570](https://github.com/robmorgan/phinx/issues/570)
=> Fix for issue 570: Postgres adapter constraint name for foreign keys fix.

src/Phinx/Db/Adapter/SqlServerAdapter.php, tests/Phinx/Db/Adapter/SqlServerAdapterTest.php
=> fixed dsn string connection for dblib

docs/migrations.rst, docs/seeding.rst
Updated 'Limit Option and MySQL' with BLOB sizes
=> Documentation improvements for MySQL limit options

src/Phinx/Console/Command/Migrate.php, src/Phinx/Console/Command/Rollback.php, src/Phinx/Migration/Manager.php, tests/Phinx/Migration/ManagerTest.php
I've run into this issue more than once, where I want to roll back my database to my version's release date before I roll the code back.
=> Added ability to roll back by date string.

tests/Phinx/Db/Adapter/SQLiteAdapterTest.php
This is a (possible) test for Issue #265.
=> Added test for null/default value issue in SQLiteAdapter

src/Phinx/Db/Adapter/PostgresAdapter.php, tests/Phinx/Db/Adapter/PostgresAdapterTest.php
Addresses issue https://github.com/robmorgan/phinx/issues/589
=> Add precision and scale support for Postgres numeric data type

src/Phinx/Db/Adapter/AdapterInterface.php, src/Phinx/Db/Adapter/AdapterWrapper.php, src/Phinx/Db/Adapter/MysqlAdapter.php, src/Phinx/Db/Adapter/PostgresAdapter.php, src/Phinx/Db/Adapter/SQLiteAdapter.php, src/Phinx/Db/Adapter/SqlServerAdapter.php, src/Phinx/Db/Adapter/TablePrefixAdapter.php, tests/Phinx/Db/Adapter/MysqlAdapterTest.php, tests/Phinx/Db/Adapter/PostgresAdapterTest.php, tests/Phinx/Db/Adapter/SQLiteAdapterTest.php, tests/Phinx/Db/Adapter/SqlServerAdapterTest.php
I added unit tests for this method, but not sure how extensive these need to be.
=> Added method hasIndexByName #580

docs/migrations.rst
=> Add BLOB type for MySql

.travis.yml
test if Travis can build Phinx on their new container based infrastructure.
=> try new travis container infra

src/Phinx/Console/Command/AbstractCommand.php, src/Phinx/Console/Command/Init.php, src/Phinx/Db/Adapter/MysqlAdapter.php, src/Phinx/Db/Adapter/PdoAdapter.php, src/Phinx/Db/Adapter/PostgresAdapter.php, src/Phinx/Db/Adapter/SQLiteAdapter.php, src/Phinx/Db/Adapter/SqlServerAdapter.php, src/Phinx/Db/Table.php, src/Phinx/Db/Table/ForeignKey.php, src/Phinx/Migration/Manager.php, src/Phinx/Migration/Manager/Environment.php
Cleanup after https://github.com/cakephp/migrations/pull/161
- Remove wrong returns when void
- Make stricter comparisons-
- No break on default in switch
- Consolidate functions and remove aliases in favor of actual function names
=> Cleanup code / CS

README.md
Old domain of box project is squatted!
=> Change box project lint to actual github page.

src/Phinx/Db/Adapter/MysqlAdapter.php
=> MySQL adapter add support for type YEAR - Issues #551

docs/migrations.rst
As raised in issue #682, this method is undocumented so I have added an example.
=> Add a documentation example for changeColumn() - fixes #682

docs/migrations.rst
I had to read the source to work out how to do this, so it would be helpful to include an example in the docs.
=> Add a documentation example for addForeignKey() with array params

docs/migrations.rst
=> Correct spelling of decimal

docs/configuration.rst, docs/migrations.rst
Just fix some `sphinx-build` warnings in docs.
=> Fix sphinx-build warnings

src/Phinx/Db/Table/Index.php
Add missing param, fix @return
=> Fix Docblock

src/Phinx/Db/Adapter/TablePrefixAdapter.php, tests/Phinx/Db/Adapter/TablePrefixAdapterTest.php
Hi, 
I have fixed the issue: https://github.com/robmorgan/phinx/issues/714
I hope, that helps a bit.
Best,
Sebastian
=> Fix for issue #714

composer.json, docs/migrations.rst, src/Phinx/Db/Adapter/MysqlAdapter.php
Added json type supported in MySQL version 5.7, amended documentation.
=> Add MySQL json type supported in MySQL 5.7

src/Phinx/Db/Adapter/MysqlAdapter.php, src/Phinx/Db/Table/Index.php, tests/Phinx/Db/Adapter/MysqlAdapterTest.php, tests/Phinx/Db/Adapter/MysqlAdapterUnitTest.php
Trying to solve [issue 518](https://github.com/robmorgan/phinx/issues/518), this is my first attempt at contribution, and I'm still not familiar with the codebase, so any correction and or tips to improve it are welcome
=> Add support for index limit on MySql Adapter

src/Phinx/Db/Adapter/MysqlAdapter.php, src/Phinx/Db/Table/Index.php, tests/Phinx/Db/Adapter/MysqlAdapterTest.php
This PR adds support for FULLTEXT indexes with the MySQL adapter.
=> Fixes #533. adds FULLTEXT index support for MySQL

src/Phinx/Db/Adapter/PostgresAdapter.php, src/Phinx/Db/Table.php, tests/Phinx/Db/Adapter/MysqlAdapterTest.php, tests/Phinx/Db/Adapter/PostgresAdapterTest.php, tests/Phinx/Db/TableTest.php
This PR adds table comments for Postgres and cleans up the MySQL implementation.
=> Fixes #175. adding table comments for Postgres. cleaning up MySQL

src/Phinx/Db/Adapter/AdapterInterface.php, src/Phinx/Db/Adapter/MysqlAdapter.php, src/Phinx/Db/Adapter/PdoAdapter.php, tests/Phinx/Db/Adapter/MysqlAdapterUnitTest.php
Adding varbinary column type support for MySQL.
=> Adding varbinary column type for mysql

docs/migrations.rst
Method removeColumn() is not supported in change() method according to http://docs.phinx.org/en/latest/migrations.html#the-change-method.
=> Fix - removeColumn in change() instead of up()

src/Phinx/Migration/Manager/Environment.php
=> Revert "doc block updated"

src/Phinx/Migration/Manager.php
This copies the glob brace support in migration paths
=> Support glob brace for seed paths

src/Phinx/Config/ConfigInterface.php
=> Constructor declaration removed from ConfigInterface

README.md, docs/commands.rst, docs/index.rst, docs/install.rst, docs/intro.rst, docs/migrations.rst, docs/seeding.rst
Just made some minor edits to the documentation to improve readability.
Read the doc changes and ensure that they make sense and are grammatically sound.
=> Documentation grammar and punctuation edits

docs/migrations.rst
Documentation for adding named foreign keys using the constraint parameter of the addForeignKey() method.
=> Documentation for adding named foreign keys

docs/migrations.rst
=> Add docs about MySQL table specific options

src/Phinx/Db/Adapter/MysqlAdapter.php
Extra check the array before the loop does not required
=> Remove extra checks

src/Phinx/Db/Adapter/AdapterFactory.php, src/Phinx/Db/Adapter/AdapterInterface.php, src/Phinx/Db/Adapter/AdapterWrapper.php, src/Phinx/Db/Adapter/BaseAdapter.php, src/Phinx/Db/Adapter/MysqlAdapter.php, src/Phinx/Db/Adapter/PdoAdapter.php, src/Phinx/Db/Adapter/PostgresAdapter.php, src/Phinx/Db/Adapter/ProxyAdapter.php, src/Phinx/Db/Adapter/SQLiteAdapter.php, src/Phinx/Db/Adapter/SqlServerAdapter.php, src/Phinx/Db/Adapter/TimedOutputAdapter.php, src/Phinx/Migration/Manager/Environment.php, tests/Phinx/Migration/Manager/EnvironmentTest.php
This is a first step in the task of cleaning the adapters to avoid code
duplications an possible future bugs.
Doing this refactor I discovered that there are methods in the postgres
adapter that are not part of `AdapterInterface` so I added them back.
Additionally, added a `BaseAdapter` to avoid code duplication when creating
new adapters in the future.
=> Added a TimedOutput adapter wrapper

docs/commands.rst
English is not my main language but tell me if something is wrong and i'll correct it.
=> Added documentation about PHPUnit integration

CONTRIBUTING.md, docker-compose.yml
Ok, now I just simplified docker-compose a little and actualize howto about running composer inside docker image.
So it's now same as in travis: `--prefer-lowest`
=> Fix testing under docker 3

docs/namespaces.rst
This Pull-request adds documentation for the namespacing PR created earlier this year, and should not be merged without first merging #1070
=> Documentation for PR-1070

src/Phinx/Migration/AbstractMigration.php, src/Phinx/Migration/MigrationInterface.php
Remnants of (partially duplicated) changes per @mvrhov's suggestion in PR #1164.
=> Clear migration direction nomencalture

src/Phinx/Console/Command/Migrate.php, src/Phinx/Console/Command/Status.php, src/Phinx/Console/PhinxApplication.php, src/Phinx/Db/Table/Column.php, src/Phinx/Db/Table/ForeignKey.php, src/Phinx/Db/Table/Index.php, src/Phinx/Migration/Manager.php, src/Phinx/Wrapper/TextWrapper.php
Also one string|boolean to string|bool
=> PHPdoc: integer to int

src/Phinx/Console/Command/Rollback.php
=> Small cs fix (Usage of !! cast is not allowed)

docs/migrations.rst
Doesn't work with SQLite, and apparently is only available in MySQL (See [this SO](https://stackoverflow.com/a/24479516/1012616) answer)
=> after option applies only to MySQL

docs/migrations.rst, src/Phinx/Db/Adapter/AdapterInterface.php, src/Phinx/Db/Adapter/PostgresAdapter.php, tests/Phinx/Db/Adapter/PostgresAdapterTest.php
I often use interval type in PostgreSQL, so I need an interval type support.
=> Added interval column type to PostgreSQL

composer.json
=> composer: use semver

composer.json, src/Phinx/Console/PhinxApplication.php
=> Add version to composer.json.

tests/Phinx/Console/Command/CreateTest.php, tests/Phinx/Migration/ManagerTest.php
Fix obvious error
Don't understand why travis don't catch it...
=> fix variable name

src/Phinx/Db/Adapter/MysqlAdapter.php, src/Phinx/Db/Adapter/PostgresAdapter.php, src/Phinx/Db/Adapter/SQLiteAdapter.php, src/Phinx/Db/Adapter/SqlServerAdapter.php
Also moved grouped cases to the top of the switch statement
=> Simplify getSqlType types with default name

src/Phinx/Migration/Manager.php
I was writing a new migration, and just forgot a semicolon at the end of a statement.  It took half an hour for me to figure it out, as phinx does not report errors when loading a migration file, it just exits silently:
```
$ ./vendor/bin/phinx status -e current -vv
Phinx by CakePHP - https://phinx.org. 0.9.2
using config file ./phinx.php
using config parser php
using migration paths 
- /var/www/html/db/migration
ordering by creation time
```
I added error reporting, and verbose logging:
```
$ ./vendor/bin/phinx status -e current -vv
Phinx by CakePHP - https://phinx.org. 0.9.2
using config file ./phinx.php
using config parser php
using migration paths 
- /var/www/html/db/migration
ordering by creation time
Migration file db/migration/20180312095838_predef_questions.php
Valid migration …
```
=> Improve error reporting when loading migration file

src/Phinx/Db/Adapter/SQLiteAdapter.php, tests/Phinx/Db/Adapter/SQLiteAdapterTest.php
Ensure primary key auto-incrementing columns are not null
=> Fix SQLite identity nullability

src/Phinx/Db/Adapter/PdoAdapter.php
Insert into phinxlog with many schemes
Resolves #575
=> Quote Table Name - fix issue #575

docs/seeding.rst
Documented the `getDependencies` method with an example and a brief description of what it does and how to use it.
=> Documented the `getDependencies` method.

docs/migrations.rst, src/Phinx/Db/Adapter/MysqlAdapter.php
Simple enough change, need this for the migration to work https://github.com/odan/phinx-migrations-generator/pull/31/commits/3c487874d7ade08bd171dcc7f4422f19bcd2c7c0
=> Add support for ROW_FORMAT table option

.travis.yml, composer.json, docs/migrations.rst, src/Phinx/Db/Adapter/AdapterInterface.php, src/Phinx/Db/Adapter/AdapterWrapper.php, src/Phinx/Db/Adapter/MysqlAdapter.php, src/Phinx/Db/Adapter/PdoAdapter.php, src/Phinx/Db/Adapter/PostgresAdapter.php, src/Phinx/Db/Adapter/SQLiteAdapter.php, src/Phinx/Db/Adapter/SqlServerAdapter.php, src/Phinx/Migration/AbstractMigration.php, src/Phinx/Migration/MigrationInterface.php, tests/Phinx/Db/Adapter/MysqlAdapterTest.php, tests/Phinx/Db/Adapter/PostgresAdapterTest.php, tests/Phinx/Db/Adapter/SQLiteAdapterTest.php, tests/Phinx/Db/Adapter/SqlServerAdapterTest.php
Support for a more feature reach query builder has been asked for
multiple times. Creating query builders is difficult, so better use
one that already exists.
=> Added a Query builder through the cakephp/database package

src/Phinx/Db/Action/Action.php, src/Phinx/Db/Action/AddForeignKey.php, src/Phinx/Db/Action/AddIndex.php, src/Phinx/Db/Action/CreateTable.php, src/Phinx/Db/Action/DropForeignKey.php, src/Phinx/Db/Action/DropIndex.php, src/Phinx/Db/Action/DropTable.php, src/Phinx/Db/Adapter/AdapterInterface.php, src/Phinx/Db/Adapter/AdapterWrapper.php, src/Phinx/Db/Adapter/DirectActionInterface.php, src/Phinx/Db/Table.php, src/Phinx/Db/Table/ForeignKey.php, tests/Phinx/Db/Adapter/PdoAdapterTest.php, tests/Phinx/Db/Adapter/ProxyAdapterTest.php, tests/Phinx/Migration/Manager/EnvironmentTest.php, tests/Phinx/Migration/ManagerTest.php
=> Clean imports

src/Phinx/Db/Table.php, tests/Phinx/Db/TableTest.php
https://github.com/cakephp/phinx/issues/1381
=> ISSUE-1381 Table::saveData() is expected to reset pending changes

src/Phinx/Db/Adapter/PostgresAdapter.php, tests/Phinx/Migration/ManagerTest.php, tests/Phinx/Migration/_files/postgres/20180516025208_test_not_empty_snapshot_pgsql.php
and also fixed an error in dropping foreign keys this test detected
=> Added full integration test for postgres

docs/migrations.rst, src/Phinx/Db/Table.php, tests/Phinx/Db/TableTest.php
=> Add Table->getColumn() function

README.md, src/Phinx/Db/Adapter/SQLiteAdapter.php, tests/Phinx/Db/Adapter/SQLiteAdapterTest.php
Ability to add multiple columns whilst using sqlite adapter. unit tests added ^^
=> Sq lite alter columns

Dockerfile
- unzip command not available
- execute as root not allowed
=> Fix Composer warnings in Docker

docs/migrations.rst
Updates the docs to use the change method instead of the up/down paradigm within the docs as that's the recommended way to use Phinx.
=> Update table examples to use change method

src/Phinx/Db/Adapter/MysqlAdapter.php, src/Phinx/Db/Adapter/PostgresAdapter.php, src/Phinx/Db/Adapter/SQLiteAdapter.php, src/Phinx/Db/Table/Column.php, tests/Phinx/Db/Adapter/MysqlAdapterTest.php, tests/Phinx/Db/Adapter/PostgresAdapterTest.php, tests/Phinx/Db/Adapter/SQLiteAdapterTest.php
Fixes #1013 and replaces PR #1258
=> Fix decimal info getColumns()

src/Phinx/Migration/Manager/Environment.php
When only using a DSN, I received the error that no adapter was specified.  Found the DSN parser was never called, so the adapter was never set.
=> Fix DSN parsing

docs/migrations.rst
=> fixes a minor typo in migrations.rst

src/Phinx/Db/Adapter/SqlServerAdapter.php, tests/Phinx/Db/Adapter/SqlServerAdapterTest.php
=> [SqlServer] Fix SqlServer syntax after making precision alias of limit

src/Phinx/Db/Adapter/PdoAdapter.php, src/Phinx/Db/Adapter/SQLiteAdapter.php, tests/Phinx/Db/Adapter/SQLiteAdapterTest.php
=> Revert "Fix for issue #1535"

src/Phinx/Db/Table.php, tests/Phinx/Db/TableTest.php
=> Fix inserting multiple rows without zero key

.travis.yml, src/Phinx/Migration/Manager.php
Resolves https://github.com/cakephp/phinx/pull/1603
=> Fix PHP7.4

src/Phinx/Db/Adapter/SQLiteAdapter.php, tests/Phinx/Db/Adapter/SQLiteAdapterTest.php
=> Fix #1583 Incorrect removing/changing columns for SQLite

composer.json, src/Phinx/Console/Command/Create.php, src/Phinx/Console/Command/Init.php, src/Phinx/Console/Command/SeedCreate.php, src/Phinx/Console/Command/Test.php
With Symfony 5.0.0 out, added 5.x dependencies.
Greetings from #SymfonyHackday
=> Upgrade to Symfony 5

index.html
This PR fixes the Phinx screencast checkout flow by switching from Plasso (now defunct) to Stripe.
=> Fix Screencast Checkout Flow

index.html
phinx.org currently shows the latest version as being 0.10.8. This updates that version per the step listed in the wiki page https://github.com/cakephp/phinx/wiki/Releasing-a-new-version-of-Phinx.
=> Update version on phinx.org

composer.json
Alternative to https://github.com/cakephp/phinx/pull/1663
Refs: https://github.com/cakephp/app/issues/758
=> fix dependency

.travis.yml, composer.json, phpstan-baseline.neon, phpstan.neon
https://github.com/cakephp/app/issues/758
=> 0.next - Upgraded phpstan to 0.12 and added baseline config

src/Phinx/Db/Adapter/MysqlAdapter.php, src/Phinx/Db/Adapter/PdoAdapter.php, src/Phinx/Db/Adapter/PostgresAdapter.php, src/Phinx/Db/Adapter/SQLiteAdapter.php, src/Phinx/Db/Adapter/SqlServerAdapter.php, tests/Phinx/Db/Adapter/MysqlAdapterTest.php, tests/Phinx/Db/Adapter/PostgresAdapterTest.php, tests/Phinx/Db/Adapter/SQLiteAdapterTest.php, tests/Phinx/Db/Adapter/SqlServerAdapterTest.php
This PR adds new option `fetch_mode` for PDO connections and gives ability to redefine default PDO data fetch mode.
=> Add fetch_mode option support for PDO adapters

README.md
=> Fix links for EN docs in README

src/Phinx/Migration/MigrationInterface.php
=> Changes query return type to mixed

composer.json, src/Phinx/Config/Config.php
=> make symfony/yaml optional and check if it is installed for usage

UPGRADE_0.6.md, composer.json
=> Use stable dependencies.

phpstan-baseline.neon, phpstan.neon, src/Phinx/Console/Command/Breakpoint.php, src/Phinx/Console/Command/Create.php, src/Phinx/Console/Command/Migrate.php, src/Phinx/Console/Command/SeedCreate.php, src/Phinx/Db/Adapter/AbstractAdapter.php, src/Phinx/Db/Adapter/AdapterFactory.php, src/Phinx/Db/Adapter/AdapterInterface.php, src/Phinx/Db/Adapter/SqlServerAdapter.php, src/Phinx/Db/Plan/Plan.php, src/Phinx/Db/Table.php, src/Phinx/Migration/AbstractMigration.php, src/Phinx/Migration/Manager.php, src/Phinx/Migration/MigrationInterface.php
=> Cleanup for major

src/Phinx/Db/Adapter/MysqlAdapter.php, tests/Phinx/Db/Adapter/MysqlAdapterTest.php
This is a new PR based on the code of @winkbrace in PR #1292
Its pretty much the same code, modified slightly to work with newer changes. Like winkbrace, I've not touched the PostgreSQL-variant or other variants of this feature.
=> Add schema-support to MysqlAdapter

docs/en/configuration.rst, src/Phinx/Config/Config.php, src/Phinx/Config/ConfigInterface.php, src/Phinx/Console/Command/SeedCreate.php
=> Add support to configure custom seeder base class

src/Phinx/Util/Util.php, tests/Phinx/Util/UtilTest.php
Allow single letter words and initialisms as per issue #267.
=> Relax migration & seed class name restrictions

src/Phinx/Db/Adapter/AdapterInterface.php, src/Phinx/Db/Adapter/AdapterWrapper.php, src/Phinx/Db/Adapter/MysqlAdapter.php, src/Phinx/Db/Adapter/PdoAdapter.php, src/Phinx/Db/Adapter/PostgresAdapter.php, src/Phinx/Db/Adapter/ProxyAdapter.php, src/Phinx/Db/Adapter/SQLiteAdapter.php, src/Phinx/Db/Adapter/SqlServerAdapter.php, src/Phinx/Db/Adapter/TablePrefixAdapter.php, src/Phinx/Db/Adapter/TimedOutputAdapter.php, src/Phinx/Db/Table/Column.php, tests/Phinx/Db/Adapter/SQLiteAdapterTest.php
Part of https://github.com/cakephp/migrations/pull/457
Needed for https://github.com/cakephp/migrations/issues/355
=> Add support for tinyint. Fix bool issue.

README.md
Resolves https://github.com/cakephp/phinx/issues/1026
=> Document limitations

src/Phinx/Console/Command/Test.php
=> Better document environment option for test command

src/Phinx/Db/Adapter/SQLiteAdapter.php, tests/Phinx/Db/Adapter/SQLiteAdapterTest.php
If a table within sqlite had been made with table level constraints (e.g. foreign key constraint), it would then throw an exception on attempting to add any further columns. This is due to 16c83d1 appending the new column at the end of the create table SQL, after any constraints. This patch modifies it so that it will inject the new column after the last existing column, which will place it before any constraints.
Closes #1843
=> Fix adding columns to existing sqlite table with table constraints

README.md
There was no interaction for > 1 year now. 
Dead.
=> Remove chat badge

src/Phinx/Db/Adapter/PostgresAdapter.php
Fixes merge conflicts and such in #1072
Original PR message: 
> postgres support for migrations in schema. fixes #930
=> bugfix: support for migration in postgresql schema

src/Phinx/Console/Command/AbstractCommand.php, src/Phinx/Console/Command/Create.php, src/Phinx/Console/Command/ListAliases.php, src/Phinx/Console/Command/SeedCreate.php, src/Phinx/Util/Util.php
as per commit 2b7036ec684337a69d33d794b6f9652656bfde84
=> Consistent output of shortened file paths

docker-compose.yml, src/Phinx/Db/Adapter/MysqlAdapter.php, src/Phinx/Db/Adapter/PostgresAdapter.php, src/Phinx/Db/Adapter/SqlServerAdapter.php, src/Phinx/Db/Table/Index.php, tests/Phinx/Db/Adapter/MysqlAdapterTest.php, tests/Phinx/Db/Adapter/PostgresAdapterTest.php, tests/Phinx/Db/Adapter/SqlServerAdapterTest.php
=> Index column sort order #1661

src/Phinx/Db/Adapter/SqlServerAdapter.php, tests/Phinx/Db/Adapter/SqlServerAdapterTest.php
=> tinyint and smallint in sqlserver #1907

src/Phinx/Db/Adapter/PostgresAdapter.php, src/Phinx/Db/Adapter/SqlServerAdapter.php, src/Phinx/Db/Table/Index.php, tests/Phinx/Db/Adapter/PostgresAdapterTest.php, tests/Phinx/Db/Adapter/SqlServerAdapterTest.php
Resolves https://github.com/cakephp/phinx/issues/1903
=> Add support for include clause when adding an index #1903

docs/en/migrations.rst
=> Add documentation on new index features #1911 

composer.json
https://github.com/cakephp/phinx/issues/2044
=> check Symfony 6

composer.json
This is from my tools run
The composer generate part also re-generates the other parts, but looks now normalized and OK to me.
=> Fix up allow-plugins config

src/Phinx/Db/Adapter/PostgresAdapter.php, src/Phinx/Db/Table/Column.php, tests/Phinx/Db/Adapter/PostgresAdapterTest.php
Working on #2070 . Implementing IDENTITY for column in PostgresAdapter.
=> Implement identity in PostgresAdapter
